### ISSUE TITLE
"Skip to canvas" button is showing when having a large circular icon

### ISSUE THREAD

**Issue by wbern** [primer/view_components#1023]
With pull request #884 , we noticed that the "Skip to canvas" on the left pane is constantly showing. It does not look too great.

Is this intended?

![image](https://user-images.githubusercontent.com/25477382/155274513-af2a5ea1-195d-4438-8481-d47eb1c3598e.png)

**Comment by jonrohan** [comment]
I'm not seeing this, can you provide more details?
