### ISSUE TITLE
Preview Deploys on Pull Requests with JavaScript changes don't include those changes

### ISSUE THREAD

**Issue by hectahertz** [primer/view_components#1042]
# Problem

When there's a Pull Request with JavaScript changes the Preview Deploy doesn't include those changes as it loads the released version instead.

See the code with this logic [here](https://github.com/primer/view_components/blob/main/docs/src/@primer/gatsby-theme-doctocat/components/head.js#L25).

# Proposed solution

Modify that logic so it treats Preview Deploy environments as development environments.

**Comment by hectahertz** [comment]
Related https://github.com/primer/view_components/issues/1048

**Comment by khiga8** [comment]
I think I addressed this in: https://github.com/primer/view_components/pull/1248, https://github.com/primer/view_components/pull/1259 🚀
