### ISSUE TITLE
LinkComponent adding extraneous whitespace

### ISSUE THREAD

**Issue by SamMorrowDrums** [primer/view_components#1106]
Hi, I just wanted to mention that the `Primer::LinkComponent` appears to add spaces automatically, which is often desirable, or a no-op depending on where it is in the markup. However, there is no way to remove them which means that in order to use a period/full-stop at the end of a sentence, you are forced to directly use an `<a>` tag manually.

As a concrete example, these were both ViewComponents, however the latter I had to convert into an anchor tag because otherwise I couldn't end the sentence without `Privacy Policy .` rendering with the extra space.

So:

```erb
<%= render(Primer::LinkComponent.new(href: "#")) { "Terms of Use" } %> and
<a href="/copilot/signup#privacy-placeholder">Privacy Policy</a>.
```

Renders `Terms of use and Privacy Policy.` and:

 ```erb
<%= render(Primer::LinkComponent.new(href: "#")) { "Terms of Use" } %> and
<%= render(Primer::LinkComponent.new(href: "#")) { "Privacy Policy" } %>.
```

Renders `Terms of use and Privacy Policy .` for me. I looked and I can see `<a> text </a>` rather than `<a>text</a>` which I believe is because [the erb](https://github.com/primer/view_components/blob/main/app/components/primer/link_component.erb) does this:

```
<%= render Primer::BaseComponent.new(**@system_arguments) do %>
  <%= content %>
  <%= tooltip %>
<% end %>
```
And I think unfortunately to actually behave correctly it might need to look like this:

```
<%= render Primer::BaseComponent.new(**@system_arguments) do %><%= content %><%= tooltip %><% end %>
```

**Comment by guo-chris** [comment]
👋 Hi, I think this is still an issue. I have a couple places ([issue](https://github.com/github/c2c-actions-experience/issues/6071); usages in github/github code [1](https://github.com/github/github/blob/e9bc4e88cbb57d761387d2cc4bab836909cb9442/app/components/actions/workflow_runs/old_attempt_banner_component.html.erb#L3-L6), [2](https://github.com/github/github/blob/e9bc4e88cbb57d761387d2cc4bab836909cb9442/app/views/checks/_checks_header.html.erb#L20-L23)) where I am seeing this regression in prod and can still reproduce it locally even with this fix. I've tried poking around at it and I'm not able to figure out what's wrong, so I'd appreciate any help with this. 

Something that I've noticed with this fix is that the actual link does not contain the space anymore, but something is still producing an extra space. I've tried a few different things with how I use the component too, like putting the text in a do-end block, putting the text in curly braces, and ending with a `-%>`, but they all produce the same result. 

Before: 
<img width="251" alt="Screen Shot 2022-04-28 at 9 12 51 PM" src="https://user-images.githubusercontent.com/61271066/165885124-b6eab8fa-7c50-44d4-9733-14a39ad32ff6.png">
<img width="221" alt="Screen Shot 2022-04-28 at 9 13 26 PM" src="https://user-images.githubusercontent.com/61271066/165885125-e4a0e95c-3fca-40f6-8ccc-d6c37610dc21.png">


After:
<img width="268" alt="Screen Shot 2022-04-28 at 9 22 12 PM" src="https://user-images.githubusercontent.com/61271066/165885129-5d8be2c4-44c7-4dbe-b0fe-1db09df8f3b2.png">
<img width="255" alt="Screen Shot 2022-04-28 at 9 22 41 PM" src="https://user-images.githubusercontent.com/61271066/165885130-46f570b6-3856-4d85-8370-43fc7276ddcd.png">

How I reproduced: 
1. Create a new github/github codespace
2. Clone the [`primer/view_components`](https://github.com/primer/view_components) repo
3. Change line in Gemfile for `"primer_view_components"` to local path
4. `script/server` (which re-bootstraps successfully)
5. Navigate to page with link
