### ISSUE TITLE
Autocomplete component examples do not appear on docs site and lookbook

### ISSUE THREAD

**Issue by jamieshark** [primer/view_components#1133]
![image](https://user-images.githubusercontent.com/5520141/165317209-8add755e-efc3-4813-b6ef-1c126b234347.png)

Seems like wherever we are sending the request for the endpoint while searching in the autocomplete is 404'ing.

Seems like the [controller exists](https://github.com/primer/view_components/blob/main/demo/app/controllers/auto_complete_test_controller.rb), but maybe we're just not routing correctly or the response is not coming back in an acceptable format.

**Comment by camertron** [comment]
Fixed by https://github.com/primer/view_components/pull/1709
