### ISSUE TITLE
Render previews as doc examples

### ISSUE THREAD

**Issue by camertron** [primer/view_components#1154]
We have the ability now to render and assert against previews in tests, and in general we're thinking quite a bit about reusing previews in more places to avoid duplication. It would be really cool to be able to use previews as examples when generating docs as well.

**Comment by khiga8** [comment]
We have the opposite of what you're suggesting right now where we generate previews from the YARD doc examples in the component files, then run tests against those. 😆

If you run `bundle exec rake docs:preview`, it generates component previews by grabbing the code examples in our YARD docs.   ([docs.rake preview task](https://github.com/primer/view_components/blob/main/lib/tasks/docs.rake#L366))

We then have a browser test that runs accessibility checks against by visiting the generated preview URL. ([doc_examples_axe_test.rb](https://github.com/primer/view_components/blob/main/test/system/doc_examples_axe_test.rb#L30)).
