### ISSUE TITLE
System arguments `color` valid values differ from LabelComponent's `scheme` valid values

### ISSUE THREAD

**Issue by cheshire137** [primer/view_components#1285]
👋🏻 Something I noticed when trying to coordinate an Octicon's `color` with a LabelComponent's `scheme` was that the valid values for each aren't the same. Compare:

color:

> Text color. One of :accent, :attention, :closed, :danger, :default, :done, :inherit, :muted, :on_emphasis, :open, :severe, :sponsors, :subtle, or :success.

-- https://primer.style/view-components/system-arguments#color

scheme:

> One of :accent, :attention, :danger, :default, :done, :info, :orange, :primary, :purple, :secondary, :severe, :sponsors, :success, or :warning.

-- https://primer.style/view-components/components/label

Common values:

- `:accent`
- `:attention`
- `:danger`
- `:default`
- `:done`
- `:severe`
- `:sponsors`
- `:success`

Differences:

- `:subtle` is a valid `color` but is not a valid `scheme`
- `:closed` is a valid `color` but is not a valid `scheme`
- `:inherit` is a valid `color` but is not a valid `scheme`
- `:muted` is a valid `color` but is not a valid `scheme`
- `:on_emphasis` is a valid `color` but is not a valid `scheme`
- `:open` is a valid `color` but is not a valid `scheme`
- `:subtle` is a valid `color` but is not a valid `scheme`
- `:info` is a valid `scheme` but is not a valid `color`
- `:warning` is a valid `scheme` but is not a valid `color`
- `:secondary` is a valid `scheme` but is not a valid `color`
- `:purple` is a valid `scheme` but is not a valid `color`
- `:primary` is a valid `scheme` but is not a valid `color`
- `:orange` is a valid `scheme` but is not a valid `color`

I wanted to bring this up because I think some/all of the different values could actually probably work for both components, just based on my understanding that all these colors are coming from Primer variables like in https://primer.style/css/utilities/colors.

**Comment by lesliecdubs** [comment]
Hi @cheshire137, thanks for reporting this! It definitely seems like something that should get addressed. We're going to move this into our backlog to explore improving it in the future.

**Comment by lesliecdubs** [comment]
Not stale

**Comment by cheshire137** [comment]
Are we still not stale, @lesliecdubs? The bot is insistent. 😅

**Comment by lesliecdubs** [comment]
@cheshire137 I think this is still a valid issue, though it's unlikely we will have resources within Primer Engineering to address it in the near future. Please feel free to reopen in the "Unprioritized backlog" if you'd like to keep this on the radar for future improvement.

**Comment by cheshire137** [comment]
> Please feel free to reopen in the "Unprioritized backlog" if you'd like

Thanks! Sorry, is that a milestone/project/repo/label?

**Comment by lesliecdubs** [comment]
Sorry for the obtuse instruction 🤦🏻‍♀️ I will go ahead and reopen this issue and move it to the "Unprioritized backlog" on our team project board.
