### ISSUE TITLE
NavigationList::Item should allow a Tooltip to render

### ISSUE THREAD

**Issue by lindseywild** [primer/view_components#1289]
## Description

There have been a few instances where we've needed truncated NavigationList::Items to have a Tooltip associated with them. The issue is that applying an `id` applies it to the `<li>`, when a Tooltip should be applied to an interactive element (in this case, the nested `<a>` tag). We need a way to apply an `id` to the `<a>` and have the Tooltip render next to it in the DOM. Right now, people are applying a `title` attribute to the truncated text which is inaccessible for many users.

## User Story

As a user of the NavigationList::Item, I want to apply a Tooltip to truncated items so that any user can see what the truncated value is.

## Requirements
- A user can pass an `id` to the underlying `<a>` tag (perhaps a slot for `anchor_id`?)
- A Tooltip needs to render _next to_ the `<a>` tag in the DOM

**Comment by langermank** [comment]
@lindseywild is this requirement only for items that are links (a href)? I'm wondering if we should also add support to items that have an `onClick` on the `li` element for menu type scenarios (so not navigational). Even though the `li` isn't a semantic button, is it valid to offer a tooltip on the `li` if it has an `onClick` event?

**Comment by lindseywild** [comment]
@langermank Yes, it's only for interactive elements (in this case, the `<a>`) -- I am not too familiar with the NavigationList::Item, so I'm not sure if you could pass in a `<button>` instead, but it would be applicable for that as well! It wouldn't be applicable to the `<li>`, though, even if it does have a click handler on it.

**Comment by langermank** [comment]
This has been addressed with the [new PVC](https://primer.style/view-components/lookbook/inspect/primer/alpha/action_list/default) `ActionList` component, in turn impacting `NavList` 😄
