### ISSUE TITLE
Support CSS class names like `color-text-success`

### ISSUE THREAD

**Issue by enriikke** [primer/view_components#129]
👋 hi there! I was working with some css classes today and received an error when I tried to apply `classes: "color-text-success"` to a `Primer::OcticonComponent`. I tried removing the `classes` keyword and using `color: "text-success"` but that got translated to `text-text-success` as the class. I tried a few other combinations but couldn't get that particular class to work out. 

I'm wondering if:

- Could we add support for classes like `color-text-success`?
- Should something like `color-text-success` be allowed under the `classes` keyword?

Thanks so much for looking into this! ❤️

**Comment by manuelpuyol** [comment]
Hi @enriikke! We added support for functional colors 😄 
you can use `color: :text_success` to generate `color-text-success`, but I do believe you may want to use `color: :icon_success` to generate `color-icon-success` since you are using it with an octicon

**Comment by enriikke** [comment]
Awesome!! Thank you @manuelpuyol ✨
