### ISSUE TITLE
Document the need to `include Primer::ViewHelper` in order to use the helpers

### ISSUE THREAD

**Issue by kjg** [primer/view_components#1311]
The [Octicon docs](https://primer.style/view-components/components/octicon) mention possible use of the `primer_octicon` helper and the [PrimerOcticon cop](https://github.com/primer/view_components/blob/5e9003eb32740c7a18864f2e6d7d51642e31d615/lib/rubocop/cop/primer/primer_octicon.rb#L21) corrects all usage of the `octicon` helper to be `primer_octicon` instead, but the docs don't make it clear how to get the `primer_octicon` helper to work.

It appears that one must either have `include Primer::ViewHelper` in their ApplicationHelper or `helper Primer::ViewHelper` in their ApplicationController (or any other more specific controller). I'd suggest the [Getting Started](https://primer.style/view-components/) page is updated to include this info as part of the Installation

**Comment by lesliecdubs** [comment]
👋🏻 Hi @kjg, thanks for reporting this! We would welcome a PR to the docs; I believe [this is the file](https://github.com/primer/view_components/blob/main/docs/content/index.md) to edit. Let us know if we can help!
