### ISSUE TITLE
Missing space or wrong content in timeAgo component

### ISSUE THREAD

**Issue by lukasoppermann** [primer/view_components#1348]
Hey,
I just noticed that on the [timeAgo preview](https://primer.style/view-components/components/timeago) there is a missing space between `ago` and the month `Nov`. I am not sure if this is just this preview or small bug in the component.
Or is this a bug in the docs, as I would assume that `Nov 28, 1989` is not supposed to show up and after a while it tends to disappear.  

`33 years agoNov 28, 1989`

<img width="1010" alt="Screenshot 2022-09-05 at 16 17 26" src="https://user-images.githubusercontent.com/813754/188469731-8cc47d35-710e-4a17-a1cc-1d6da68602a0.png">

**Comment by lesliecdubs** [comment]
I think this can this closed now that PVC `TimeAgo` has transitioned to `RelativeTime`: https://primer.style/view-components/components/beta/relativetime. @lukasoppermann please reopen if this is incorrect!
