### ISSUE TITLE
Support for FileField

### ISSUE THREAD

**Issue by raivil** [primer/view_components#1349]
Hello,
I'm planning on adding file upload support to my app (and other fields types, such as rich text area) and I'm wondering what would be a good strategy to support it.

I've added a discussion at https://github.com/primer/view_components/discussions/1346 and a link to a PR

What would be a good strategy to support those fields?
Do you have suggestions other than the implemented on the discussion post (https://github.com/primer/view_components/discussions/1346) that would be simpler?

Thank you!

**Comment by lesliecdubs** [comment]
Hi @raivil, thanks for opening up this conversation! I'll add this to the team's radar and we'll aim to get back to you by next week.

**Comment by danielnc** [comment]
@lesliecdubs any updates here? we are trying to do the same thing and finding it hard to know what would be the best strategy for this

**Comment by lesliecdubs** [comment]
Sorry for the delay with our response, @raivil and @danielnc!

@joelhawksley as first responder this week, do you have any thoughts or recommendations on this?

**Comment by camertron** [comment]
Hey @raivil, apologies, I've been heads-down on a work item this week and haven't had a chance to catch up with my notifications until now.

I responded to the discussion you linked, but long story short: there's not a simpler way at the moment. I'd be happy to pair sometime next week if you like 😄
