### ISSUE TITLE
Expand support for passing in hex colors

### ISSUE THREAD

**Issue by joelhawksley** [primer/view_components#139]
In https://github.com/primer/view_components/pull/138/files#r527100055, @kevinsawicki rightly pointed out that our support for passing in color hex values for system arguments is inconsistent.

We should probably make this feature consistent across other color-related system arguments.

What do you think @emplums?

**Comment by emplums** [comment]
It makes sense to make these consistent for both bg and color, but I wonder what the implications of this API are for the color modes work?

**Comment by joelhawksley** [comment]
@emplums you make a good point about the color modes work. 

Perhaps we should think about this in the opposite direction: should we have this API at all?
