### ISSUE TITLE
FlexItemComponent doesn't support flex-basis

### ISSUE THREAD

**Issue by brphelps** [primer/view_components#147]
I found myself wanting to use flex-basis (namely, a % basis), and FlexItemComponent doesn't have anything exposed to pass it in alongside normal args (like flex_auto). 

Ex: 
`<%= render(Primer::FlexItemComponent.new(flex_auto: true)) do %>`
=>
`<%= render(Primer::FlexItemComponent.new(flex_auto: true, flex_basis: "33%")) do %>`

Note: It's also very common for people specifying flex in a way that "contains" stuff to use overflow: hidden to make sure that the flex boundaries are respected. I suspect that should be supported as well.

**Comment by manuelpuyol** [comment]
Closing since the component is deprecated and `BoxComponent` should be used instead
