### ISSUE TITLE
How to add empty option to select

### ISSUE THREAD

**Issue by raivil** [primer/view_components#1485]
Hi,

I'm trying to add an empty option to a select on a form, but I'd like some thoughts on how to do that properly.
Currently adding a caption will not add a empty option.
This code will result in the image below.
```
my_form.select_list(name: :some_name,
                              label: :thumbnail_page_video
                              caption: :label_select_one_option) do |field|
```
![image](https://user-images.githubusercontent.com/2623565/195441622-eb87ebf1-7c67-4e7c-b3d2-4d48d07b47e5.png)

What I'm doing is adding an empty option hardcoded
```
field.option(label: "", value: "") 
add_more_options_based_on_a_list
```
Although it looks small and simple, any thoughts on how to improve it?

Best,

**Comment by camertron** [comment]
Hey @raivil, it looks like the way to add a blank option is to pass `include_blank: true` to the `select` method on the Rails form builder. Due to a bug, the `SelectListInput` class doesn't currently pass these arguments on to Rails, but #1505 should fix that.

**Comment by raivil** [comment]
thank you, @camertron!
