### ISSUE TITLE
Measure and reduce the number of allocations made by Primer::Classify

### ISSUE THREAD

**Issue by BlakeWilliams** [primer/view_components#155]
When investigating a page's performance related to allocations, I found that `Primer::Classify` was performing a significant number of allocations.

The places making the most allocations were:

- [Primer::Classify#extract_class](https://github.com/primer/view_components/blob/main/lib/primer/classify.rb#L155)
- `Hash#except`
- [Line 187 of Primer::Classify#extract_class](https://github.com/primer/view_components/blob/main/lib/primer/classify.rb#L187)

We should try to measure, then reduce the number of allocations made in that class since it can be a hot path for primer components.

**Comment by manuelpuyol** [comment]
@BlakeWilliams with https://github.com/primer/view_components/pull/197 and https://github.com/primer/view_components/pull/166

should we close this issue?

**Comment by BlakeWilliams** [comment]
I think we're probably good to close this for now, but can probably write some follow-up issues to prevent regressions, catch new keys, refactor, etc.

Thanks for the reminder!
