### ISSUE TITLE
Using nested fields_for

### ISSUE THREAD

**Issue by raivil** [primer/view_components#1637]
Hi,
what would be a proper way to use nested fields_for on form classes? I'm struggling to find a good solution.

Example:
```ruby
class MainForm < ApplicationForm
  form do |main_form|
    main_object = config_form.builder.object
    main_form.fields_for(:child_1, main_object.child_1, include_id: false) do |builder|
      builder.text_field(name: :some_field, label: :the_label)
      builder.fields_for(:grandchild, main_object.child_1.grandchild, include_id: false) do |other_builder|
        GrandchildForm.new(other_builder)
      end
    end
  end
end
```

The non component version is something like: 
```ruby
   <%= form_for main_object, url: the_path(main_object), method: :patch do |form| %>
     <%= form.fields_for(:child_1, main_object.child_1, include_id: false) do |child_form| %>
       <%= child_form.text_field :field_from_child_1 %>
       <%= child_form.fields_for(:grandchild, main_object.child_1.grandchild, include_id: false) do |other_builder| %>
         <%= other_builder.text_field :filed_from_grandchild %>
       <% end %>
     <% end %>
   <% end %>
```
With primer form components, this can be achieved using multiple form classes, where each would have a `fields_for`

**Comment by lesliecdubs** [comment]
@camertron has been working on Rails forms lately. Cameron, are you able to advise here?

**Comment by camertron** [comment]
Hey @raivil, wow it's so cool you're using the forms stuff! Please first let me apologize for the lack of documentation 🥴 I'm hoping we'll be able to dedicate some time to writing it up, maybe next quarter.

It is possible to nest forms using `fields_for`, but each of the forms must be a separate form class, i.e. a class that inherits from `Primer::Forms::Base` (or `ApplicationForm`). So for example:

```ruby
class MainForm < ApplicationForm
  form do |main_form|
    # `child` must be a relation or method on the parent's object, usually an active record object
    main_form.fields_for(:child) do |builder|
      ChildForm.new(builder)
    end
  end
end

class ChildForm < ApplicationForm
  form do |child_form|
    # `grandchild` must be a relation or method on the child's object, usually an active record object
    child_form.fields_for(:grandchild) do |builder|
      GrandchildForm.new(builder)
    end
  end
end

class GrandchildForm < ApplicationForm
  form do |grandchild_form|
    # grandchild's fields go here
  end
end
```

I noticed you used `:child_1` in your example, which indicates there's more than one child at that nesting level. If that's the case, you should be able to call `fields_for` multiple times, eg:

```ruby
class MainForm < ApplicationForm
  form do |main_form|
    main_form.fields_for(:child_1) do |builder|
      Child1Form.new(builder)
    end

    main_form.fields_for(:child_2) do |builder|
      Child2Form.new(builder)
    end
  end
end
```

You can also render multiple forms together using the `FormList` class:

```erb
<%= primer_form_with(model: main_object) do |f| %>
  <%= render(
    Primer::Forms::FormList.new(
      Child1Form.new(f.fields_for(:child_1)),
      Child2Form.new(f.fields_for(:child_2))
    )
  ) %>
<% end %>
```

Hope that helps!

**Comment by raivil** [comment]
Thank you, @camertron.
That resolves my issue.
I've already been using isolated classes for each nested form so far but wanted to know if a form would support a simpler way similar to what rails does.
Maybe on future versions!
Anyway, thanks for the documentation!

**Comment by jonrohan** [comment]
Closing for now, open if you have any other problems
