### ISSUE TITLE
Primer::NavigationList show_more_item click issue 

### ISSUE THREAD

**Issue by vsvipul** [primer/view_components#1702]
In Primer::NavigationList with show_more_item, clicking on show_more_items shows a small highlight on all the items in this list, and I believe this is a bug.
P.S. In the video, you’ll not see in the first click, but on the second one. 
https://user-images.githubusercontent.com/21038781/206975337-f3b5adec-b368-4dfa-8a15-d4502bf2f2e5.mov

**Comment by camertron** [comment]
Should be resolved by https://github.com/primer/view_components/pull/1756
