### ISSUE TITLE
Duplicated "extra" (renders_one)  when alignment is on the right side.

### ISSUE THREAD

**Issue by raivil** [primer/view_components#1790]
Hi,

I'm seeing a very weird behavior with the usage of `Primer::Alpha::TabPanels`.

The `extra`  (renders_one) is being displayed both on the left and right side if configured to be on the right side.

This is happening on production environment only, which is even more weird to me. On Staging environment it works as expected. 
I was able to reproduce it locally after changing env vars to "production", but unfortunately not to the point I can create a PR to share.
 
Some env settings:
```
Ruby 3.1.2p20
rails 7.0.4.2
gem "primer_view_components", "~> 0.0.119"
gem "view_component", "~> 2.82.0"
gem "view_component-contrib", "~> 0.1.2"
```

Teh code have a custom component that is using `Primer::Alpha::TabPanels`. This custom component has a `renders_one :extra_content`.
This is the component code

```ruby
class Shared::TabPanel::Component < ApplicationViewComponent
  option :label
  renders_many :items # (code simplified)

  renders_one :extra_content
end

<%= render(Primer::Alpha::TabPanels.new(label: label, display: :flex, body_arguments: { flex: 1 })) do |component| %>
  <% items.each do |item| %>
    <% component.with_tab(id: item.id, selected: item.selected) do |t| %>
      <% t.with_text { item.title } %>
      <% t.with_panel(classes: class_for(:panel)) do %>
        <%= item %>
      <% end %>
    <% end %>
  <% end %>

  <% component.with_extra(align: :right) do %>
    <%= extra_content %>
  <% end %>
<% end %>
```

What I noticed while debugging (with simple `puts` and changing the gem code locally) is that `@align` always starts with `:left` 
and then is changed to `:right`
on the code from 
https://github.com/primer/view_components/blob/972dd7bd92e79b2e8b54555f91770c4c1b280709/app/components/primer/alpha/tab_panels.html.erb#L3-L9
so the line with `<%= extra if @align == :left %>` always evaluates to true and renders the `extra`. 

Any help is appreciated.
Thank you for the great work on primer.
Best,

**Comment by camertron** [comment]
Aha! https://github.com/primer/view_components/blob/b07e010c3e4b1be745b0da95f20fa3e2da8810f8/app/lib/primer/tabbed_component_helper.rb#L14

**Comment by camertron** [comment]
In development only, the `validate_single_selected_tab` method fetches all the tabs, which causes view_component to evaluate `TabPanel`'s content, which calls `extra` _before_ render. In production, `extra` is only called _during_ render, and we see the behavior I explained above.
