### ISSUE TITLE
Feature request: link directly to opened Dialog

### ISSUE THREAD

**Issue by megan-arellano** [primer/view_components#1807]
Right now, there is not an simple way for me to create a link to an opened dialog. It would be useful if there was an option to create a link that open a page with an opened dialog. For example, the following screenshot shows [a url that corresponds in part to the name of the event](https://education.github.com/events?utf8=%E2%9C%93&q=category%3ASpecial#special-GitHub-Code-Innovation-Series---Nigeria), and the page opens with the focus on the modal that shows details for the event.
![Screenshot 2023-02-02 at 12 48 32 PM](https://user-images.githubusercontent.com/109243577/216434586-3aa72069-3609-434a-a4d0-086a09be0e7e.png)

**Comment by lesliecdubs** [comment]
@github/accessibility-reviewers can you weigh in on whether there are any concerns around setting up modal deep-linking, so a user could link someone directly to a page with a dialog already in an open state?

**Comment by lesliecdubs** [comment]
@khiga8 as accessibility First Responder this week, could you weigh in on whether there are any accessibility concerns around setting up modal deep-linking like this, so that a user could link someone directly to a page with a dialog already in an open state?
