### ISSUE TITLE
Title and text of counter component are redundant

### ISSUE THREAD

**Issue by brittanyellich** [primer/view_components#1815]
The title and the text on a counter component are the same, which was called out by the WAVE accessibility chrome extension as being a redundant issue for accessibility. Our proposed fix would be to move the [final else section of this code block](https://github.com/primer/view_components/blob/b07e010c3e4b1be745b0da95f20fa3e2da8810f8/app/components/primer/beta/counter.rb#L74-L87), so that the title isn't added if it is the same as the text of the counter component, but we wanted to get more thoughts/insight before opening a PR.

![Screen Shot 2023-02-07 at 2 14 03 PM](https://user-images.githubusercontent.com/25957322/217378930-8a5b5904-7eab-4ef0-9aa7-4221b13482d0.png)

![Screen Shot 2023-02-07 at 2 15 06 PM](https://user-images.githubusercontent.com/25957322/217379080-09269d3c-8140-4ce4-b242-efd25d06ab50.png)

**Comment by jonrohan** [comment]
Thanks for the bug, I do believe this is an issue. I think our logic for when to show a title could use an update. If you feel like sending a PR we'd be super appreciative.
