### ISSUE TITLE
NavList::Section `show_more_item` slot uses Primer CSS class

### ISSUE THREAD

**Issue by strackoverflow** [primer/view_components#1843]
👋 Hello! I am unable to use the `show_more_item` slot of the `NavList::Section` component because it is using a [Primer CSS class under the hood](https://github.com/primer/view_components/blob/462bfb63e83d6a3535cd68c3c9b2176bb5e27717/app/components/primer/alpha/nav_list/section.rb#L31-L34), which causes the System Arguments exception to throw:

<img width="1152" alt="Screenshot 2023-02-22 at 5 57 00 PM" src="https://user-images.githubusercontent.com/431533/220791018-a8f0ebf0-7769-4193-aa0b-3ff6456bb1fe.png">

I can try to cut a PR to fix this tomorrow but wanted to flag this!

**Comment by camertron** [comment]
Woops, sorry about this @strackoverflow! I'm taking a look now.

**Comment by strackoverflow** [comment]
Thank you, I appreciate it!
