### ISSUE TITLE
How to document SlotV2 arguments

### ISSUE THREAD

**Issue by manuelpuyol** [primer/view_components#188]
Related: https://github.com/primer/view_components/pull/185#discussion_r569558545

We need to document arguments for our component's slots. Currently we document directly on their `Slot` class, but with the introduction of SlotV2 the syntax has changed and we need to decide how to document them.

**Comment by joelhawksley** [comment]
@manuelpuyol thanks for raising this issue.

My main desires for this change is that the documentation for slots is presented consistently regardless of whether they are declared as classes or lambdas.

Do you have any ideas in mind?
