### ISSUE TITLE
NavList::Group - `show_more_item` slot text color cannot be changed

### ISSUE THREAD

**Issue by strackoverflow** [primer/view_components#1886]
There's a minor issue with the `show_more_item` slot in `NavList::Group`: the text color of the link cannot be set via system arguments as it [appears to be hardcoded to `:accent`](https://github.com/primer/view_components/blob/b3b94e989f51fcc776cf312208bd4dcadde31161/app/components/primer/alpha/nav_list/group.rb#L33).

**Comment by camertron** [comment]
Design first responder: are there any design concerns with changing the text color of the "Show more" nav item?

**Comment by mperrotti** [comment]
@strackoverflow - could you share more details about your use-case? I'm not understand why we'd need to change the color.

**Comment by strackoverflow** [comment]
Hi @mperrotti! Yes, our use case was that the design for GitHub's global navigation update called for a `muted` color scheme for the "show more items" link in the left hand side panel. 

We ended up working around this, but in general I think we expected that things like text color would be customizable with system arguments. Totally a minor thing for us though.
