### ISSUE TITLE
Primer::Beta::Blankslate does not allow custom call to action

### ISSUE THREAD

**Issue by heynan0** [primer/view_components#1904]
The primary action, for example, from https://github.com/primer/view_components/blob/main/app/components/primer/beta/blankslate.rb, will always renders as a button link. 

There does not seem to be a way to inject different content at the end of the blankslate container.

Example use cases:

A primary call to action that looks exactly like the example, but is backed by a form that submits to a POST request:

https://github.com/github/github/blob/8d3630c421ad803d77dabc524efbefb4252e2ab8/app/components/repos/security/policy_component.html.erb#L47-L56

A custom button that is defined on its own component:

```
<%= render Primer::Beta::Blankslate.new(spacious: true) do |component| %>
  ...
  <% component.with_primary_action(SomeCustomButtonComponent) %>
<% end %>
```

The `Primer::BlankslateComponent` allowed passing anything to its block so it would render inside.

**Comment by lesliecdubs** [comment]
Hi @heynan0 👋🏻 , can you share any more about the specific product launch or area where you have a need for this functionality so that we can better prioritize the enhancement request?

**Comment by heynan0** [comment]
@lesliecdubs, the security policy page uses a custom primary action button:

https://github.com/heynan0/one-commit/security/policy

Code:

https://github.com/github/github/blob/8d3630c421ad803d77dabc524efbefb4252e2ab8/app/components/repos/security/policy_component.html.erb#L47-L56

**Comment by howdyray** [comment]
@heynan0 We will be discussing this in our primer design patterns discussion and will follow up on next steps.

**Comment by mperrotti** [comment]
@heynan0 - does the example from https://github.com/github/github/blob/8d3630c421ad803d77dabc524efbefb4252e2ab8/app/components/repos/security/policy_component.html.erb#L47-L56 get you closer to a solution?

cc @camertron

**Comment by camertron** [comment]
@mperrotti unfortunately that example uses `Primer::BlankslateComponent` whereas @heynan0's question is about `Primer::Beta::Blankslate`. I believe custom CTA content was intentionally disallowed.

**Comment by mperrotti** [comment]
Oops! My mistake.

**Comment by camertron** [comment]
I'm going to close this for now. @heynan0, please feel free to re-open if this is still an issue for you :)
