### ISSUE TITLE
Documentation for Deprecated Components -> BlankslateComponent is missing

### ISSUE THREAD

**Issue by heynan0** [primer/view_components#1930]
There is a link on the sidebar of the production website that links to BlankslateComponent , under the category Deprecated Components:

<img width="326" alt="Screenshot 2023-04-04 at 11 38 12 AM" src="https://user-images.githubusercontent.com/58703271/229845026-efb1aee0-7572-4522-afc5-80eccf6e5239.png">

However, it goes to a page that does not exist (404):

<img width="1061" alt="Screenshot 2023-04-04 at 11 36 46 AM" src="https://user-images.githubusercontent.com/58703271/229845093-43cd91bf-4a48-4a0b-ab82-e440107dccbf.png">

**Comment by lesliecdubs** [comment]
Hi @heynan0, thanks for letting us know!

@colebemis @camertron do either of you have ideas on what may have happened to make this docs link 404 here?
