### ISSUE TITLE
The appearance of `Button`'s trailing visual counter needs adjustment

### ISSUE THREAD

**Issue by scotttesler** [primer/view_components#1936]
The [`trailing_visual_counter` Button slot](https://primer.style/view-components/components/beta/button#trailing_visual) does not look good on `primary` buttons (I haven't checked other schemes).

In light, contrast is low:

<img width="174" alt="Screenshot 2023-04-04 at 3 46 27 PM" src="https://user-images.githubusercontent.com/586779/229903288-3f2ea1ac-4e55-484b-851c-116349605e90.png">

In dark dimmed, the color looks wrong:

<img width="167" alt="Screenshot 2023-04-04 at 3 48 01 PM" src="https://user-images.githubusercontent.com/586779/229903575-be59dc09-1418-4d75-bef4-2881a57877fb.png">

- It looks like the Counter is still using `--color-btn-counter-bg` instead of `--color-btn-primary-counter-bg`, despite the Button being `scheme: :primary`.
- Explicitly passing `scheme: :primary` to `trailing_visual_counter` also does not seem to be taking effect.

**Comment by simurai** [comment]
The old `.btn` seems to use a separate `--color-btn-primary-counter-bg` variable for primary buttons:

![Screenshot 2023-04-18 at 14 29 31](https://user-images.githubusercontent.com/378023/232680165-8fc7a204-451d-4480-ab61-722a47dca08b.png)

So it probably should be fixed when using that also for the new `Button`.
