### ISSUE TITLE
rake tasks :test in conflict with main application.

### ISSUE THREAD

**Issue by safeforge** [primer/view_components#1963]
@jonrohan It was introduced in #1378 and I'm wondering how is better to fix it. Maybe wrap it in the `primer` namespace? 

You can reproduce creating a new rails application with the following commands:

```
rails new buggy --css postcss --js esbuild -d sqlite3;
```

if you try to run the `rake test` you can see the default rails result.

```
Running 0 tests in a single process (parallelization threshold is 50)
Run options: --seed 53935

# Running:



Finished in 0.001425s, 0.0000 runs/s, 0.0000 assertions/s.
0 runs, 0 assertions, 0 failures, 0 errors, 0 skips
``` 

Let's add `primer_view_components` in order to reproduce the conflict:

```
bundle add primer_view_components;
echo 'require "view_component"\nrequire "primer/view_components/engine"' >> config/application.rb;
```

Running the `rake test` again we'll see a different output with a different exit status

```
....

File does not exist: /tmp/buggy/test/accessibility_test.rb

rake aborted!
Command failed with status (1)
```

**Comment by jonrohan** [comment]
Thanks for the feedback, we'll look into changing the name.

**Comment by camertron** [comment]
Can we potentially stop including the rake tasks in the gem?

**Comment by camertron** [comment]
See: https://github.com/primer/view_components/pull/2015
