### ISSUE TITLE
ActionMenu: "is_dangerous" option does not change the styling of item

### ISSUE THREAD

**Issue by aguevara23** [primer/view_components#1993]
The documentation includes an example of an [ActionMenu with a "danger" item](https://primer.style/view-components/components/alpha/actionmenu#with-danger-item), signified by the `is_dangerous: true` option. However, the presence of this option does not change the styling or functionality of the menu item.

This is in contrast with the [React component](https://primer.style/react/ActionMenu), which uses red text for menu items with the `danger` variant. 

**ViewComponent**
<img width="626" alt="image" src="https://user-images.githubusercontent.com/15002980/236993942-ca7fe22c-b52c-430e-95bf-1b8cda3a4f81.png">

**React Component**
<img width="247" alt="image" src="https://user-images.githubusercontent.com/15002980/236993610-f8d63d22-1364-4e5a-96a2-220afb4a0b07.png">

**Comment by camertron** [comment]
Hey @aguevara23, sorry for the confusion! The `is_dangerous` argument is a left-over from the old experimental version of the component. As you identified, the corresponding option in the alpha version is `scheme: :danger`. Thanks for pointing this out! Should be fixed momentarily by https://github.com/primer/view_components/pull/2010
