### ISSUE TITLE
Primer::Alpha::Dialog can't be set to be disabled

### ISSUE THREAD

**Issue by jalafel** [primer/view_components#2001]
When initializing a Dialog component with a disabled button, the click event still propagates and opens a dialog modal.

```
<%= render(Primer::Alpha::Dialog.new(
  title: "Dialog Example",
  id: "my-dialog",
)) do |d| %>
  <% d.with_show_button(disabled: true) { "Show Dialog" } %>
  <% d.with_body do %>
    <p>Some content</p>
  <% end %>
  <% d.with_footer do %>
    <%= render(Primer::ButtonComponent.new(data: { "close-dialog-id": "my-dialog" })) { "Cancel" } %>
    <%= render(Primer::ButtonComponent.new(scheme: :primary)) { "Submit" } %>
  <% end %>
<% end %>
```

**Comment by lesliecdubs** [comment]
👋 @keithamus could you take a look at this when you have a moment? If it's a larger fix, let me know and we can look at scheduling in time to fix.

**Comment by jalafel** [comment]
When you click the button, is the event still triggered? For me, the dialog button is styled to be cancelled but when clicked the event is triggered!

**Comment by keithamus** [comment]
I didn’t check if the event propagates but the dialog most definitely did not open for me.

**Comment by jalafel** [comment]
https://github.com/primer/view_components/assets/12400507/52c15f08-c65d-41a4-8a31-b72fdbf3ad93

**Comment by keithamus** [comment]
It might be the case that for some reason the button isn't a `<button>` in the markup? I've raised #2021 which I think would fix that case, but it would be great to confirm by seeing the actual markup featured in the videos you've posted
