### ISSUE TITLE
Overlay does not work on Edge Dev 114

### ISSUE THREAD

**Issue by Tyriar** [primer/view_components#2005]
Repro:

1. Open https://primer.style/view-components/components/alpha/overlay in Edge Dev channel
2. Scroll down and click Show Overlay

![Recording 2023-05-11 at 06 18 38](https://github.com/primer/view_components/assets/2193314/02adde40-1044-4145-b3d0-82cc701b59f5)

This affects GitHub's pull request review; I am currently unable to post reviews in this browser and have to run a second browser as a result.

![Recording 2023-05-07 at 06 04 46 (1)](https://github.com/primer/view_components/assets/2193314/83eb7f08-10ab-4786-b782-bd3968d2d502)

Please treat this with high priority as when v114 moves to stable it will be a much larger problem. I'm not sure if Chrome Canary has the same problem.

**Comment by jonrohan** [comment]
This is fixed in latest release https://github.com/primer/view_components/releases/tag/v0.1.9 and will be fixed in dotcom when https://github.com/github/github/pull/273071 merges.
