### ISSUE TITLE
ActionMenu keyboard navigation: opening the dropdown menu does not focus the first item

### ISSUE THREAD

**Issue by aguevara23** [primer/view_components#2007]
When a user opens the ActionMenu dropdown by pressing `enter` or `space`, none of the menu items have focus. 

After pressing `arrow down`, the focus will start to move between items. Then when closing and reopening the menu, the index of the focused item is the same as when the menu was closed. So if the second item is focused and the menu is closed, upon re-opening the menu the second item will be focused instead of the first. 

It seems that for each ActionMenu on the page, the "index" of the focused item is not reset after closing the menu. I believe the expected behavior is that the first item should always have focus after opening the dropdown.

**Screen recording** 

https://github.com/primer/view_components/assets/15002980/676292ae-3a77-47c4-970b-77348e6188f0

**Comment by camertron** [comment]
Hey @keithamus, can you take a look at this one? Not sure what's going on here, as we specifically have a [test](https://github.com/primer/view_components/blob/65745bf4c8044806a23e741eac0daf8e1fe65d53/test/system/alpha/action_menu_test.rb#L123) for this.

**Comment by keithamus** [comment]
#2002 fixed this, I forgot to add the ref. This can be closed, as https://github.com/primer/view_components/releases/tag/v0.1.9 has the fix.
