### ISSUE TITLE
TabPanel does not tab into other tabs

### ISSUE THREAD

**Issue by jalafel** [primer/view_components#2076]
The TabPanel component doesn't allow tab to reach other tabs after tabbing into the panel. 

Video from Playground:
https://github.com/primer/view_components/assets/12400507/29dd8a7e-6190-4c18-8f1b-b06c7c302b4f

**Comment by camertron** [comment]
Hey @jalafel, thanks for asking about this!

As it happens, the behavior you're seeing is intentional. Instead of using the tab key to reach other panels, use your arrow keys. Here's the [documentation](https://primer.style/design/components/tab-panels#other-a11y-guidance) with more information 😄
