### ISSUE TITLE
ActionMenu icon button tooltip doesn't go away when menu is opened

### ISSUE THREAD

**Issue by strackoverflow** [primer/view_components#2081]
This has been reported by some users as the redesigned global navigation has rolled out. The `ActionMenu`, when used with an `IconButton`, has a tooltip that appears on hover. This tooltip doesn't go away when the menu is opened though and kind of awkwardly overlaps with the menu:

<img width="230" alt="screenshot of the Action Menu with a tooltip overlaying behind the menu content" src="https://github.com/primer/view_components/assets/431533/1c83a58a-ea68-40e5-8525-c404b5a44bdc">

https://github.com/primer/view_components/assets/431533/6b7fe99c-8557-4bf1-b46c-a8978b1ac89d

Perhaps we can update this to somehow only show tooltips when the menu is closed?

**Comment by jonrohan** [comment]
@keithamus This seems related to the menu now using popover, and the old tooltip not using popover.

I could see we either need to update the Tooltip js to dismiss any popovers when toggled, or convert the tooltip component to also use the popover api. What are your thoughts?

**Comment by keithamus** [comment]
Yes the Tooltip will need to be upgraded to popover. I can do that
