### ISSUE TITLE
Flash's dismiss button improperly placed

### ISSUE THREAD

**Issue by scotttesler** [primer/view_components#2112]
For the [`dismissible: true` Flash option](https://primer.style/design/components/flash/rails/beta), the dismiss button doesn't properly place itself in the top-right of the box:

<img alt="dismiss button improperly placed" src="https://github.com/primer/view_components/assets/586779/372b9012-0e71-4239-9d19-8f039869ae0b">

```ruby
<%= render(Primer::Beta::Flash.new(dismissible: true)) do %>
  <%= render(Primer::Beta::Text.new(tag: :h4)) { "Title" } %>
  <%= render(Primer::Beta::Text.new(color: :muted, tag: :p)) do %>
    Some text.
  <% end %>
<% end %>
```

**Comment by jonrohan** [comment]
This is a known problem with the Flash component and multi lines, we'd recommend using the Banner component instead which is better suited for this https://primer.style/view-components/lookbook/inspect/primer/alpha/banner/playground?dismissible=true&content=This+is+a+flash+message%21This+is+a+flash+message%21This+is+a+flash+message%21This+is+a+flash+message%21This+is+a+flash+message%21This+is+a+flash+message%21This+is+a+flash+message%21This+is+a+flash+message%21This+is+a+flash+message%21This+is+a+flash+message%21This+is+a+flash+message%21This+is+a+flash+message%21This+is+a+flash+message%21&description=afdsfs
