### ISSUE TITLE
„New“ menu always shown on iPad

### ISSUE THREAD

**Issue by mr-manuel** [primer/view_components#2209]
**Describe the bug**
The „new“ menu is always shown.

**To Reproduce**
1. Login to GitHub on an iPad in Firefox
2. See the open menu

**Expected behavior**
The menu should only be shown, if opened.

**Screenshots**
![IMG_2215](https://github.com/primer/css/assets/12592765/df8c8ade-d881-4400-9c25-024094d7f442)

**Tablet (please complete the following information):**
- Device: iPad Pro 11“ 2020
 - OS: iPadOs 17.0
 - Browser Firefox
 - Version 115.1

**Additional context**
In Safari it works. I already cleared the cache of Firefox and reinstalled the app.

**Comment by mr-manuel** [comment]
since a few days one more menu is constantly shown…

![IMG_2226](https://github.com/primer/view_components/assets/12592765/d7b88c4c-04cd-4191-a958-9d20af93fc40)

**Comment by lesliecdubs** [comment]
Thanks for reporting! 

@keithamus we were thinking you might have some insight here as we think this is a `popover` compatibility issue in Firefox. Do you happen to know the ETA for that support? If it's going to be a while, is there a polyfill for Firefox or potentially a CSS solution we could make sure is set up to work properly?

**Comment by keithamus** [comment]
This is indeed a Firefox compatibility issue with `popover` on iOS/iPad OS 17. This is because Safari 17 has enabled `popover`, which includes applying the `@support` rules for `:popover-open`, but sadly it doesn't enable the `popover` functionality for web views (of which Firefox is one). 

I don't know what we can do to fix this one annoyingly. I'll keep looking for a solution though.

**Comment by lesliecdubs** [comment]
Thanks. Moving this to the backlog for now to revisit and resolve once the polyfill support has landed.

**Comment by mr-manuel** [comment]
Should the change already be visible?

**Comment by keithamus** [comment]
Not just yet, I'll come back here and let you know when we're deploying.

**Comment by keithamus** [comment]
This is the WebKit bug for reference: https://bugs.webkit.org/show_bug.cgi?id=263405.

**Comment by keithamus** [comment]
Following up as promised; the patch just went out and this is now resolved @mr-manuel.

**Comment by mr-manuel** [comment]
Thank you! I confirm that this is fixed now :-)
