### ISSUE TITLE
Feature: Avatar Stack Component

### ISSUE THREAD

**Issue by abeidahmed** [primer/view_components#226]
I'd like to make a PR for the [avatar stack component](https://primer.style/css/components/avatars#avatar-stack). However, I see that currently, `view_components` has two `Slotable` modules,
- `ViewComponent::Slotable`
- `ViewComponent::SlotableV2`

If I am to make a PR, which `module` should I use?

**Comment by manuelpuyol** [comment]
https://github.com/primer/view_components/pull/240
