### ISSUE TITLE
ActionMenu does not work inside Dialog

### ISSUE THREAD

**Issue by jalafel** [primer/view_components#2261]
Hi Rails team! I'm trying to render an ActionMenu within a Dialog and I'm coming up against an error. [This PR had fixed a different bug](https://github.com/primer/view_components/pull/2212) when ActionMenus were used to open a Dialog, but introduced a new one as the ActionMenu doesn't propagate any events inside a Dialog component, so is not functional. 

Here's a video I setup in my local development:

https://github.com/primer/view_components/assets/12400507/c7fc20c5-4627-4f17-88b6-313e62ab2132

**Comment by lesliecdubs** [comment]
@keithamus would you mind taking a look at this and letting me know what [size you would assign the work](https://github.com/github/primer/blob/main/how-we-work/labels.md#size-labels) (GitHub staff only), given your familiarity with these components? This will help us make the call on when to prioritize it.

**Comment by keithamus** [comment]
Pebble size. I'll look closely tomorrow and if I can, I'll raise a fix.
