### ISSUE TITLE
Link underlines are rendered on hover even when underline:false is specified

### ISSUE THREAD

**Issue by lesliecdubs** [primer/view_components#2277]
> @camertron This has resulted in underlines being rendered on hover when `underline:false` is set. Before the `.no-underline` class would prevent underline on hover as well. 

<img width="1052" alt="Screenshot 2023-10-04 at 6 01 51 PM" src="https://github.com/primer/view_components/assets/133359/e4bf6b03-a80d-43d0-96a0-6b2c349dffd8">

_Originally posted by @kintner in https://github.com/primer/view_components/issues/2249#issuecomment-1747876835_

**Comment by kintner** [comment]
I'm wondering if we should just add `.no-underline` to our links to fix this...

**Comment by lesliecdubs** [comment]
Notes from PVC sync:
- It looks like the default behavior of PRC links is having no underline by default, on hover underline appears: https://primer.style/react/storybook/?path=/story/components-link--default
- In https://github.com/primer/view_components/pull/2249, this same behavior was replicated in PVC

I think we could use some Primer Design input on whether this is the preferred behavior for underlines on links or not.

**Comment by tallys** [comment]
Let's discuss this at an upcoming patterns meeting, also cc @lukasoppermann and @ericwbailey

**Comment by camertron** [comment]
I can provide some context on this. We decided to allow no underline on non-nover, non-active links, but always underline links on hover. My understanding is that links are more accessible when they are distinguished visually by more than just color alone.

**Comment by jonrohan** [comment]
@kintner After discussing in the primer patterns meeting, the recommended fix here is to replace these 2 links with Button components with the invisible scheme https://view-components-storybook.eastus.cloudapp.azure.com/view-components/lookbook/inspect/primer/beta/button/leading_visual
