### ISSUE TITLE
Promote ButtonComponent to beta

### ISSUE THREAD

**Issue by srt32** [primer/view_components#228]
TODO:

* The API of [`ButtonComponent.new(type: :button)`](https://github.com/primer/view_components/blob/main/app/components/primer/button_component.rb#L49) seems like a smell we should resolve.

**Comment by manuelpuyol** [comment]
@joelhawksley how do you feel about promoting it now since we changed `button_type` to `scheme`?

**Comment by joelhawksley** [comment]
@manuelpuyol All good on my end 👍🏻
