### ISSUE TITLE
No `indeterminate` state styling in check boxes

### ISSUE THREAD

**Issue by aaron-contreras** [primer/view_components#2287]
It looks like the `Primer::Alpha::CheckBox` component is missing the indeterminate state styles as compared to the React components. Are there any plans to add these styles to Primer View Components as well?

**Comment by lesliecdubs** [comment]
Hi @aaron-contreras 👋 Thanks for checking in about this. We don't have any current plans to prioritize the indeterminate state for PVC `Checkbox`, but the CSS for this feature does already exist over here: https://github.com/primer/view_components/blob/cc44952c1c84e4fcd3ad6dc786db7211cdb82d36/app/components/primer/alpha/text_field.pcss#L640. 

If you or someone else would like to contribute this back into PVC using the Primer React state and provided CSS as a model, we'd be happy to review! As a reference, here is the contribution guide for PVC: https://github.com/primer/view_components/blob/main/docs/contributors/README.md. Let us know if you have questions!
