### ISSUE TITLE
Deprecate Flex and FlexItem components in favor of BoxComponent

### ISSUE THREAD

**Issue by srt32** [primer/view_components#229]
Let's choose to deprecate them in favor of `BoxComponent` usage or let's figure out what we need to do to promote them to beta.

**Comment by srt32** [comment]
Primer Components currently say

> The Flex component behaves the same as the Box component except that it has display: flex set by default.
>
> Previously, a Flex.Item component was used for flex item specific properties; Box now contains all those properties and should be used in its place.


so, at minimum we could deprecate `FlexItem` to be consistent.

Assuming we're agreed on that, we are left to discuss if we want to keep `FlexComponent`.

cc/ @joelhawksley @manuelpuyol thoughts?

**Comment by joelhawksley** [comment]
@srt32 I think it might be worth looking at how we use these components internally and consider refactoring them to use Box. If that goes well, deprecation sounds like the right route.

**Comment by manuelpuyol** [comment]
I believe that `flex` properties could be part of `Classify (system_arguments)`
