### ISSUE TITLE
Primer DetailsComponent does not support opener customization from caret

### ISSUE THREAD

**Issue by megan-arellano** [primer/view_components#2339]
Hello! I have been working on an [accessibility issue](https://github.com/github/accessibility-audits/issues/6103) where the remediation was to use a DetailsComponent. The DetailsComponent replaced an chevron-right that, when clicked, reveals more text. To approximate the same functionality, I did `component.with_summary(button: false)` to get a standard details element with a caret opener. However, the standard caret does not match GitHub's [progressive disclosure standard](https://primer.style/ui-patterns/progressive-disclosure); instead, the opener should still be a chevron-right. As best I can tell, the DetailsComponent doesn't support this currently. Could the DetailsComponent support customizing the opener?

**Comment by lesliecdubs** [comment]
Thanks for filing this request! 

I'd like to get Primer Design's confirmation that the [`Details` component](https://primer.style/components/details/) should technically not rely on the caret ([as it currently does in Rails](https://view-components-storybook.eastus.cloudapp.azure.com/view-components/lookbook/inspect/primer/beta/details/without_button)) as per [this progressive disclosure advice](https://primer.style/ui-patterns/progressive-disclosure#progressive-disclosure-ui-patterns) - and should instead use a chevon icon pointed right. Is that correct?

**Comment by megan-arellano** [comment]
😅 Sorry about the delayed response @lesliecdubs !

> I'd like to get Primer Design's confirmation that the [Details component](https://primer.style/components/details/) should technically not rely on the caret ([as it currently does in Rails](https://view-components-storybook.eastus.cloudapp.azure.com/view-components/lookbook/inspect/primer/beta/details/without_button)) as per [this progressive disclosure advice](https://primer.style/ui-patterns/progressive-disclosure#progressive-disclosure-ui-patterns) - and should instead use a chevon icon pointed right.

^ Yes, this is what I believe should happen.

**Comment by megan-arellano** [comment]
@lesliecdubs Apologies again for letting this languish. Small nudge/I'm curious -- is there any other information I can provide? Will this issue be the best way for me to follow any decisions regarding this request?

**Comment by mperrotti** [comment]
@megan-arellano - can we get a screenshot of what you're building so we can have more context?

**Comment by megan-arellano** [comment]
Hi @mperrotti, I was replacing an existing component with a Primer Details one. In the video below is the original behavior, where a user can click or tab on a right facing chevron to reveal more information about their classroom assignments.


https://github.com/primer/view_components/assets/109243577/1f2dc47d-7e87-4632-b1d9-af5bae2edbda


When replacing the existing container with the Details component, the chevron becomes a triangle pointed right, which is the violation of progressive disclosure as I understand it. This is shown in the video below.



https://github.com/primer/view_components/assets/109243577/cc9c5476-ab15-410b-8f56-2cf434fbf27c

**Comment by mperrotti** [comment]
Ok, I think I understand the issue now. I think we just need to update the [Rails implementation](https://view-components-storybook.eastus.cloudapp.azure.com/view-components/lookbook/inspect/primer/beta/details/playground) to align with the [progressive disclosure guidelines](https://primer.style/ui-patterns/progressive-disclosure).

What do you think @jonrohan ?
