### ISSUE TITLE
`Primer::Beta::Flash` `dismissable` action is inactive

### ISSUE THREAD

**Issue by akabiru** [primer/view_components#2394]
Hi there 👋🏾 , thanks for the great work on this.

### 🐛 `Primer::Beta::Flash` `dismissable` action is inactive

Seems we need a [catalyst action similar to the banner component](https://github.com/primer/view_components/blob/main/app/components/primer/alpha/banner.html.erb#L26)

![flash-dismiss](https://github.com/primer/view_components/assets/17295175/c294c69c-1e6c-42c8-9315-e5a90fab3afa)

**Comment by camertron** [comment]
Hey @akabiru, thanks for asking about this 😄 To my knowledge, the `Flash` component has never supported dismissal via the "x" button. It was created before we started attaching behavior via web components. You'll have to do one of the following:

1. Attach dismiss behavior yourself in javascript.
2. Use the `Banner` component instead, which is eventually going to replace `Flash`.
