### ISSUE TITLE
The `Primer/SystemArgumentInsteadOf` linter doesn't report on marketing utility classes

### ISSUE THREAD

**Issue by francisfuzz** [primer/view_components#2430]
## Summary

We have [utilities for marketing typography](https://github.com/primer/css/blob/main/docs/stories/utilities/MarketingTypography.mdx) that come in the form of:

- Headings: `.h0-mktg` to `.h6-mktg`
- Font styling:`.f0-mktg` to `.f6-mktg`

While reviewing a GitHub internal PR, I noticed that our application enabled this particular cop, but didn't report on one of the components that included an instance from this utility family:

```erb
            <%= render Primer::Beta::Button.new(classes: "f4-mktg") %>
```

I created a new test in `test/lib/rubocop/system_arguments_instead_of_class_test.rb` and observe that the assertions fail:

```ruby
  def test_marketing_class
    investigate(cop, <<-RUBY)
      Primer::BaseComponent.new(classes: "f4-mktg")
    RUBY

    assert_equal 1, cop.offenses.count
    assert_equal "Primer/SystemArgumentInsteadOfClass: Avoid using CSS classes when you can use System Arguments: https://primer.style/view-components/system-arguments.\n", cop.offenses.first.message
  end

## Terminal Output
# Running:

.F

Failure:
RubocopSystemArgumentInsteadOfClassTest#test_marketing_class [/workspaces/view_components/test/lib/rubocop/system_arguments_instead_of_class_test.rb:66]:
Expected: 1
  Actual: 0
```

Questions:

- Should it report on marketing utility classes?
- If so, would the team be open to me cutting a PR for this? 😸

**Comment by camertron** [comment]
Hey @francisfuzz, thanks for bringing this to our attention! A couple of questions:

1. How often are people using these marketing classes?
2. Where does the styling live for these classes? Is the entire set of them known?

> Should it report on marketing utility classes?

I'm going to say yes. I thought about potentially writing a separate linter for this, but since we have marketing stuff in PVC already, adding them to the existing set of utility classes seems ok.

> would the team be open to me cutting a PR for this?

Absolutely! The place to put them is [custom_utilities.yml](https://github.com/primer/view_components/blob/4391873d9970ef981e22d1b7360343037683c1d1/lib/tasks/custom_utilities.yml).

**Comment by francisfuzz** [comment]
> How often are people using these marketing classes?

For our internal application within the `github` org (can share on request 😉 ), my back-of-the-napkin `grep` script counted about ~195 instances of these marketing classes. I'm not sure how many people are using these marketing classes beyond our app!

> Where does the styling live for these classes? Is the entire set of them known?

From what I can tell, it's in our app's components and views folders (in the context of an HTML+ERB file). The entire set of them can be known with some updates to my script. 😸 

> I'm going to say yes. I thought about potentially writing a separate linter for this, but since we have marketing stuff in PVC already, adding them to the existing set of utility classes seems ok.

> > would the team be open to me cutting a PR for this?

> Absolutely! The place to put them is [custom_utilities.yml](https://github.com/primer/view_components/blob/4391873d9970ef981e22d1b7360343037683c1d1/lib/tasks/custom_utilities.yml).

@camertron - Wonderful, thank you! I've assigned myself to this issue and will set aside some cycles to work on this. 👍

**Comment by francisfuzz** [comment]
> Where does the styling live for these classes? Is the entire set of them known?

@camertron - I re-read your questions again and I think that I misinterpreted what you were asking, sorry!

I'm wondering if you meant where those respective headings and font stylings are defined? In that case, I believe this is it: https://github.com/primer/css/blob/main/src/marketing/type/typography.scss

**Comment by francisfuzz** [comment]
@camertron - Re-thinking this after a chat with my colleague @smashwilson 💭 

First, I'm wondering if there's a guideline of sorts for when to use these marketing utilities? Were these created solely for the GitHub Marketing team for a specific purpose, or can any GitHub team use these utilities to incorporate in their `github`-owned applications?

Also, assuming that it is okay for other GitHub teams to use these marketing utilities, is there a reason that they don't have system argument representation yet? Perhaps we should implement those in the system arguments, before implementing the changes in the linter -- does that order make sense? 

Last, is the goal for the system arguments to represent all of `primer/css`, or only a subset?

**Comment by camertron** [comment]
> my back-of-the-napkin grep script counted about ~195 instances of these marketing classes

Ok, it sounds like they're definitely worth supporting as system arguments then 😄 

> I'm wondering if you meant where those respective headings and font stylings are defined? In that case, I believe this is it:

That does mostly answer my question. Are you looking to support only the typography classes though? I see a bunch of other stuff in that [utilities directory](https://github.com/primer/css/tree/2b46b7a4b85e0a863052efe2f8012da2290178c3/src/marketing/utilities).

> First, I'm wondering if there's a guideline of sorts for when to use these marketing utilities? Were these created solely for the GitHub Marketing team for a specific purpose, or can any GitHub team use these utilities to incorporate in their github-owned applications?

That I'm not sure of 😓 I think in general, GitHub-owned applications should use Primer components first and non-marketing utility classes second. I believe those marketing utility classes were created specifically for landing pages, etc, so I would try to avoid using them outside of a marketing context. We are also always up for discussing new utility classes or updates to components to achieve styling goals.

> Also, assuming that it is okay for other GitHub teams to use these marketing utilities, is there a reason that they don't have system argument representation yet? Perhaps we should implement those in the system arguments, before implementing the changes in the linter -- does that order make sense?

Yes, that order makes sense 👍 although as I said above, we should only use them in marketing contexts.

> Last, is the goal for the system arguments to represent all of primer/css, or only a subset?

For now, system arguments only support a subset of utility classes. We add missing ones whenever there's a need.

**Comment by francisfuzz** [comment]
> That does mostly answer my question. Are you looking to support only the typography classes though? I see a bunch of other stuff in that [utilities directory](https://github.com/primer/css/tree/2b46b7a4b85e0a863052efe2f8012da2290178c3/src/marketing/utilities).

@camertron - Personally speaking, I'd like to keep the focus narrow and only support those typography classes. To your point, maybe the other stuff could wait until someone surfaces the need for it? 😉 

> That I'm not sure of 😓 I think in general, GitHub-owned applications should use Primer components first and non-marketing utility classes second. I believe those marketing utility classes were created specifically for landing pages, etc, so I would try to avoid using them outside of a marketing context. We are also always up for discussing new utility classes or updates to components to achieve styling goals.

Roger that: I can adhere to that approach for sure! 👍 

---

Based on our discussion thus far, I think the next best steps are to:

- Open a separate issue for tracking work for implementing the marketing typography classes in this repo
- Keep this issue open until that gets implemented

Is that appropriate, or should I do something different to move this forward? 💭

**Comment by francisfuzz** [comment]
Having another thought about this after chatting with my colleague @jalafel! 

One of the topics they shared was considering the ongoing work that's happening with Primer React in conjunction [Primer Brand](https://primer.style/brand). Might there be any planned or upcoming work that involves Primer Brand _also_ being implemented for Primer View Components, too? 💭 

Maybe taking that context into consideration may steer the direction of this work, where it may be wiser to hold off and see where that goes? 😅

**Comment by camertron** [comment]
> Based on our discussion thus far, I think the next best steps are

Yes, those are good next steps :) If you're up to it, we would also welcome a PR since it's unlikely we'll be able to pick this up until next year.


> Might there be any planned or upcoming work that involves Primer Brand _also_ being implemented for Primer View Components, too?

I haven't heard anything, but maybe? @lesliecdubs, can you weigh in here?

**Comment by lesliecdubs** [comment]
👋 Hi! Thanks for tagging me in here @camertron.

> One of the topics they shared was considering the ongoing work that's happening with Primer React in conjunction [Primer Brand](https://primer.style/brand). Might there be any planned or upcoming work that involves Primer Brand also being implemented for Primer View Components, too? 💭

My understanding is that the [Primer Brand library](https://primer.style/brand/) (implemented in React) is GitHub's official design system for marketing pages and experiences, and that forward-looking investments in marketing infrastructure will be happening in React, as per the [future of GitHub's UI platform](https://thehub.github.com/news/2022-10-18-react/). cc'ing @raytalks in case she has anything to add here

Given this direction I would generally be in favor of removing and/or discouraging use of marketing utilities within Primer CSS and PVC, as these [styles should now be handled by the Primer Brand library](https://primer.style/brand/getting-started/theming).

That said, I'm not super familiar with what the linter `Primer/SystemArgumentInsteadOf` does, so if there's a compelling reason to consider adding this for marketing utilities in the meantime - feel free to share more and we can keep discussing!

**Comment by camertron** [comment]
> My understanding is that ... forward-looking investments in marketing infrastructure will be happening in React

Right, that makes sense 👍 Given 1) the relatively high number of existing usages of the marketing classes, and 2) how uncomplicated it is to add them to custom_utilities.yml, I still say let's do it.

> I'm not super familiar with what the linter Primer/SystemArgumentInsteadOf does

It ensures any CSS classes passed to a component, eg. `render(FooComponent.new(classes: "f4-mtkg"))` are passed as system arguments instead, eg: `render(FooComponent.new(f_mktg: 4))`. The linter already enforces this style for many of Primer CSS's utility classes.

**Comment by lesliecdubs** [comment]
> Given 1) the relatively high number of existing usages of the marketing classes, and 2) how uncomplicated it is to add them to custom_utilities.yml, I still say let's do it.

@camertron should we consider adding these classes to Primer CSS instead of PVC, since that's where we're trying to consolidate most Rails styles these days? Or is there not an easy way to add the requested linter to PCSS? Also wanted to make sure you were of https://github.com/primer/view_components/pull/2477, as it seemed like the outcome from that work might have an effect on the direction we might want to take here (cc @jonrohan).

**Comment by francisfuzz** [comment]
> We talked about this at our latest PVC sync meeting and I discovered we're https://github.com/primer/view_components/pull/2477 enforcement of utility classes as system arguments. You can still use them, but we will stop enforcing them. Let me know if that changes anything on your end, @francisfuzz.

@lesliecdubs & @camertron - Happy New Year! 🎉 Thank you both for providing such rich context to my questions. Admittedly, I'm still letting these updates settle in my mind, and I've set aside time tomorrow to make a decision for where-and-how to move this forward. 👍

**Comment by francisfuzz** [comment]
My apologies: this totally slipped my radar and that's on me. I am sorry! 😞 

After evaluating against the following context, I've decided to close this issue and leave the behavior alone, so folks can continue to optionally use marketing classes where it makes the most sense for their use case.

The first reason is related to [what Leslie had shared](https://github.com/primer/view_components/issues/2430#issuecomment-1874586435): I don't think Marketing-related content should be introduced in Primer View Components, given the team's move to consolidate that area into Primer Brand. I think there are likely to be folks who disagree with my view, and they're more than welcome to take up that work if they so choose! 🙇 

The second reason is related to https://github.com/primer/view_components/pull/2477 along with [the example](https://github.com/primer/view_components/issues/2430#issuecomment-1874357215) Cameron shared about using the marketing classes. It got me thinking: "how are these actually defined under the hood?" 💭 

I dove in `primer/css` and was curious to see how the font size stylings were defined for those types. 

Here's the ["plain" flavor](https://github.com/primer/css/blob/207070961eff673ed83c055af6ec8d28f7002b1a/src/utilities/typography.scss#L100-L107):

```scss
/* Set the font size to #{$h4-size} */
.f4 {
  font-size: var(--h4-size, $h4-size) !important;


  @include breakpoint(md) {
    font-size: var(--h4-size, $h4-size) !important;
  }
}
```

And here's the [marketing flavor](https://github.com/primer/css/blob/207070961eff673ed83c055af6ec8d28f7002b1a/src/marketing/type/typography.scss#L59-L69):

```scss
.f0-mktg,
.f1-mktg,
.f2-mktg,
.f3-mktg,
.f4-mktg,
.f5-mktg,
.f6-mktg {
  font-family: $font-mktg;
  font-feature-settings: $mktg-font-feature-settings;
  font-weight: $font-weight-normal;
}
```

They're not exactly one-for-one, and understandably so based on previous design decisions! 

My humble take, based on these findings, is to go forward with leaving this alone, such that we give folks flexibility to choose whatever makes the most sense for their use case, which _feels_ like a better developer experience than introducing the potential friction that comes with a new linter change.
