### ISSUE TITLE
Positioning and background of Dialog is wrong when opened without a trigger button

### ISSUE THREAD

**Issue by HDinger** [primer/view_components#2581]
### Version
0.18.1

### Steps to reroduce

* Render a `Dialog` without calling `with_show_button` , e.g very simplified:
```
render(Primer::Alpha::Dialog.new(title: 'My awesome title', open: true)) do |d|
  d.with_body { 'Some modal text' }
end
```

### Actual behavior

* The dialog is not rendered in the middle of the page, but at the top.
<img width="1580" alt="Bildschirmfoto 2024-02-09 um 10 14 00" src="https://github.com/primer/view_components/assets/7457313/115d9aa2-4538-4df7-9ae8-1bdae178754d">

* The dark overlaying background is missing

### Expected behavior

* Similar to how it behaves when opened via a button, the modal should be in the middle of the page.

<img width="1579" alt="Bildschirmfoto 2024-02-09 um 10 15 09" src="https://github.com/primer/view_components/assets/7457313/8a44eecc-9f5d-443e-b236-de57535292a9">

* There should be a dark background

### Notes

Both issues are a result of pseudo-selectors not being applied, when opened without the trigger. `:backdrop` ([responsible for the dark background](https://github.com/primer/view_components/blob/main/app/components/primer/alpha/overlay.pcss#L18)) and `:modal` ([responsible for the positioning](https://github.com/primer/view_components/blob/main/app/components/primer/alpha/dialog.pcss#L167)) are only applied when the a `dialog` tag is opened via [HTMLDialogElement.showModal()](https://developer.mozilla.org/en-US/docs/Web/CSS/::backdrop#description). 

I don't know if I am missing something here, but I the fact that `show_button` is an optional slot, let's me assume that I should be able to render a `Dialog` from rails without the use of additional Javascript. I'd appreciate any input on this :)

**Comment by keithamus** [comment]
If you're using the JS API the call has changed from `.show()` to [`.showModal()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/showModal), as it is now using the native `<dialog>` element which has both. The `with_show_button` has changed to use this too.
