### ISSUE TITLE
Formally deprecate `Flash` and point people to Banner

### ISSUE THREAD

**Issue by khiga8** [primer/view_components#2599]
See [Staff-only Slack context](https://github.slack.com/archives/CGJTTJ738/p1707768948314759?thread_ts=1707524004.597779&cid=CGJTTJ738) and previous nudges pointing people to use Banner instead of Flash:

* https://github.com/primer/view_components/issues/2394#issuecomment-1828767755
* https://github.com/primer/view_components/issues/2112#issuecomment-1619177962

Given the past discussion that Banner will replace Flash, it probably makes sense to formally deprecate Flash and/or update docs to point people to Banner.

I am unsure what the formal deprecation process is like but filing for tracking!

**Comment by jonrohan** [comment]
We discussed this in the weekly PVC sync, seems reasonable to move forward with this 👍
