### ISSUE TITLE
Button with `scheme: :invisible` has different font colors 

### ISSUE THREAD

**Issue by HDinger** [primer/view_components#2663]
### Version

0.19.0

### Steps to reprdocue

* Use an `Primer::Beta::Button` with `scheme: :invisible`
* Compare how the button looks w/o a trailing or leading visual
* The issue can be seen here: https://view-components-storybook.eastus.cloudapp.azure.com/view-components/lookbook/inspect/primer/beta/button/invisible_all_visuals

<img width="919" alt="Bildschirmfoto 2024-03-05 um 08 23 46" src="https://github.com/primer/view_components/assets/7457313/027ae24c-0cf0-424c-b164-55e84b62f759">

### Actual behaviour
 
* Without an additional visual, the button font is blue
* With an additional visual it is black

### Expected behaviour

* The font color should always be the same
* I assume, the default should be black according to this specification: https://primer.style/components/button#invisible

**Comment by jonrohan** [comment]
This is expected behavior
