### ISSUE TITLE
Link ViewComponent with tooltip renders tooltip label far from link

### ISSUE THREAD

**Issue by megan-arellano** [primer/view_components#2732]
The tooltips of the Explored offers section of education.github.com/globalcampus/student have a considerable distance from their corresponding link. 

!["Microsoft Azure" tooltip is not next to Microsoft Azure logo](https://github.com/primer/view_components/assets/109243577/6b5c2932-e226-4cd5-894e-596af5f20b4e)

While exploring this issue, the `direction` attribute of the tooltip seems to not be having an effect. In other words, changing direction to `s` over `n` has no effect. 

Other engineers in the team (h/t `garman` and `smashwilson`!) have wondered if [time of load may be a factor](https://github.com/github/education-web/issues/12376#issuecomment-2023719006). More [exploration on Education issue](https://github.com/github/education-web/issues/12376).

**Comment by Toromambo** [comment]
it's not working
