### ISSUE TITLE
Update primer/css version

### ISSUE THREAD

**Issue by srt32** [primer/view_components#276]
In dotcom we have `"@primer/css": "15.2.0",` and in the Rakefile to build the docs we have `https://unpkg.com/@primer/css/dist/primer.css`, which resolves to https://unpkg.com/@primer/css@15.2.0/dist/primer.css.

--------------------------------

Ah, I see what's going on here.

The docs examples load Primer from a public CDN, not using the version we serve in dotcom. 

We _really_ need to update the PVC docs site to use the version of Primer CSS we're using on dotcom. Perhaps we could prioritize that ahead of this PR?

_Originally posted by @joelhawksley in https://github.com/primer/view_components/pull/269#discussion_r582185654_

**Comment by srt32** [comment]
@joelhawksley I think we are running on matching versions. Am I missing something?

**Comment by joelhawksley** [comment]
> @joelhawksley I think we are running on matching versions. Am I missing something?

I see that dotcom is using `"@primer/css-next": "0.0.0-6a1daf3"., which is the release candidate for v16.

**Comment by srt32** [comment]
Interesting! How should / could we keep things up to date? I can update the unpkg link manually now but this is going to break again...

**Comment by srt32** [comment]
Looking again, https://github.com/primer/css-next is a private mirror. I'm not sure that's going to work for this project...

**Comment by manuelpuyol** [comment]
Maybe @simurai could help us here?

**Comment by joelhawksley** [comment]
@colebemis would it be possible to package and serve Primer CSS in the PVC doctocat site?

**Comment by colebemis** [comment]
@joelhawksley I'm sure it's possible, but it might be tricky to scope the styles so they don't conflict with Doctocat styles.

I think the easiest solution would be to use `https://unpkg.com/@primer/css-next@canary/dist/primer.css`, which should give us the same version that dotcom uses.

When https://github.com/primer/css/pull/1131 is merged, we can go back to using `https://unpkg.com/@primer/css/dist/primer.css`.

**Comment by srt32** [comment]
Aha, I was not expecting the unpkg link for css-next to exist given the repo is private ;). I made that switch in https://github.com/primer/view_components/pull/278

**Comment by srt32** [comment]
Done via https://github.com/primer/view_components/pull/278
