### ISSUE TITLE
Fix stuck CI when actions docs build is last commit

### ISSUE THREAD

**Issue by srt32** [primer/view_components#279]
https://github.com/primer/view_components/pull/257 caused a use case where PR's can get stuck if the docs build has the last commit since actions seems not to run. I would have expected https://github.com/primer/view_components/blob/main/.github/workflows/ci.yml#L3 to mean CI would run no matter where the commit came from.

![image](https://user-images.githubusercontent.com/2181356/109163038-1fc6e580-7736-11eb-858f-8e6bb8ca011f.png)

**Comment by srt32** [comment]
From our internal actions folks:

> I believe that's expected. To prevent infinite loops of actions, any pushes done with GITHUB_TOKEN will not trigger Actions events. The workaround if you really want to and are sure you're not creating an infinite loop is to push with a personal access token or SSH key.

> I've done in the past is generate a new SSH key and add it to the repository as a deploy key. You can then pass it as a secret to the checkout action which then allows git push to use it too. https://github.com/actions/checkout#usage

**Comment by srt32** [comment]
@joelhawksley @manuelpuyol mainly braindumping to keep y'all in the loop. Does going with the deploy key idea make sense to you?

**Comment by manuelpuyol** [comment]
maybe we should check with appsec to be sure?
I don't love the idea of having a personal token/SSH used in the project's CI. If that person leaves for whatever reason CI will stop working

**Comment by srt32** [comment]
I think the SSH key can be uploaded to the repo directly so it's not tied to a specific user but I've not done this before.

**Comment by srt32** [comment]
I have one other approach that would allow us to keep using the existing (simple) auth set up. I think this would work...

1. on each push on a PR, we build the docs to make sure they are valid (they don't break) but we don't commit them.
2. on push to master, we build the docs again and then commit them there.

this has the drawback of the PR author not seeing the docs updated unless they run the docs build step themselves but gets us out of this problem. Thoughts?

**Comment by manuelpuyol** [comment]
> on push to main, we build the docs again and then commit them there.

Isn't main push-protected?

**Comment by srt32** [comment]
> Isn't main push-protected?

whoops, yes, that's how we ended up in our current approach.

**Comment by manuelpuyol** [comment]
I think the SSH approach may be good enough for us

**Comment by joelhawksley** [comment]
@koddsson didn't you suggest we go this route based on similar work Web Systems did? Perhaps you might have some context here?

**Comment by srt32** [comment]
github/catalyst publishes to a docs branch - https://github.com/github/catalyst/blob/main/.github/workflows/docs-build.yml#L36. That is also something we could consider. I'm not sure how the vercel builds are working right now.

**Comment by joelhawksley** [comment]
@srt32 that seems like it would reduce some confusion. Publishing to the same branch you're on seems like a ripe source of confusion 😅

**Comment by srt32** [comment]
I can experiment with pushing to a docs branch. @joelhawksley I think I'd need vercel access to make the config changes to publish the docs from that branch.

One issue with this change is that we currently dump the component statuses ` bundle exec rake statuses:dump` in this build too. We'd need to push this manual step back onto the dev so that file stays up to date on main. That seems like a bummer but also not the end of the world.

**Comment by joelhawksley** [comment]
@srt32 I seems like we're kind of in a pickle here. I'd be curious if @colebemis has any thoughts on what an ideal configuration would be for us.

**Comment by srt32** [comment]
I looked into using the ssh key and bumped into https://maxschmitt.me/posts/github-actions-ssh-key/, which makes it look simple.

However,[ the secrets page mentions](https://github.com/primer/view_components/settings/secrets/actions):

> Secrets are not passed to workflows that are triggered by a pull request from a fork. Learn more.

which I think means the docs can't build for users that contribute from forks. I think this means the ssh key approach will not work. Does that seem correct to y'all?

**Comment by joelhawksley** [comment]
That sounds right to me. 

I can't help but wonder if the real issue here is our need to "vendor" the results of building the docs. Perhaps we should look into alternative approaches?

**Comment by srt32** [comment]
Feels like whatever we land on here would make a great blog post and action on the marketplace ;)
