### ISSUE TITLE
BorderBox demo seems to be broken?

### ISSUE THREAD

**Issue by koddsson** [primer/view_components#281]
The scrolling of this demo seems a bit broken.

https://user-images.githubusercontent.com/318208/109176471-c2a35200-777e-11eb-8a62-e9efde260e74.mov

**Comment by manuelpuyol** [comment]
Since we are using `<iframe>` for the examples, we resize them on load to fit their content (JS hack), maybe we should move away from iframes now that we can customize doctocat: https://github.com/primer/view_components/pull/262

**Comment by koddsson** [comment]
For what it's worth, I didn't do anything after loading the demo. It loads like that for me on the initial load.

https://user-images.githubusercontent.com/318208/109177709-fe8ae700-777f-11eb-9e38-94914989d3b4.mov
