### ISSUE TITLE
Add new label to docs site for components that require JS behaviors

### ISSUE THREAD

**Issue by srt32** [primer/view_components#283]
Inspired by https://github.com/primer/view_components/pull/282/. We could do something like `Requires JS`

**Comment by manuelpuyol** [comment]
After https://github.com/primer/view_components/pull/262 is merged, we'll have more control over the doc layout and we can implement this!

**Comment by manuelpuyol** [comment]
@colebemis do you know if there is a way of customizing the layout without rewriting the `Layout` component from doctocat? #262 used to rewrite the component, but since the Storybook link was upstreamed we are using the default layout
