### ISSUE TITLE
Run accessibility audits automatically

### ISSUE THREAD

**Issue by srt32** [primer/view_components#284]
Let's find a way to use https://github.com/dequelabs/axe-core

Some options:
* https://www.npmjs.com/package/@storybook/addon-a11y
* https://github.com/microsoft/accessibility-insights-action

**Comment by khiga8** [comment]
Previous PR only addressed partially so reopening

**Comment by joelhawksley** [comment]
5/17 update: @khiga8 has another PR in progress for this issue.
