### ISSUE TITLE
Allow Storybook to be loaded without trailing slash

### ISSUE THREAD

**Issue by joelhawksley** [primer/view_components#288]
Currently, https://primer.style/view-components/stories/ must be loaded with a trailing slash. Might we be able to make it work without the trailing slash?

**Comment by manuelpuyol** [comment]
The problem here is how storybook generates its static files, using relative paths
I think we have to customize the webpack configuration Storybook uses

**Comment by manuelpuyol** [comment]
reopening because it didn't work correctly in prod :(

**Comment by manuelpuyol** [comment]
reopening because it didn't work correctly in prod :(

**Comment by manuelpuyol** [comment]
https://primer.style/view-components/stories is working now 🎉
