### ISSUE TITLE
Caption of ToggleSwitchForm is given too little space

### ISSUE THREAD

**Issue by HDinger** [primer/view_components#2943]
### Steps to reproduce

* Go to https://primer-lookbook.github.com/view-components/lookbook/inspect/primer/forms/example_toggle_switch_form
* Decrease the window size, so that the label is wrapped

### Buggy behaviour

* The caption is limited to width of the label

<img width="300" alt="Bildschirmfoto 2024-07-11 um 08 59 15" src="https://github.com/primer/view_components/assets/7457313/2e436e20-18ab-4661-920e-e286ea228b72">

### Expected

Taken from [the docs](primer.style/components/toggle-switch), the caption should span the whole witdh of the toggle switch form and not be limited to the width of the label

<img width="437" alt="Bildschirmfoto 2024-07-11 um 08 16 54" src="https://github.com/primer/view_components/assets/7457313/f08795fa-231c-4085-b6b2-ea3c05e35356">

**Comment by jonrohan** [comment]
Nice catch! We'll take a look, I think we could update the container to not get squashed like that
