### ISSUE TITLE
Add ability to set a `test_selector` on `Primer::Alpha::Item#description`

### ISSUE THREAD

**Issue by sampart** [primer/view_components#2970]
This would be really useful in tests. Thanks!

**Comment by camertron** [comment]
Hey @sampart! Anything I can help with here to get this over the finish line?

**Comment by sampart** [comment]
Thanks @camertron! As far as I'm concerned, https://github.com/primer/view_components/pull/2971 is ready, but I'm getting [odd CI failures](https://github.com/primer/view_components/actions/runs/10163397489/job/28106553608?pr=2971), so I didn't feel able to make it non-draft yet.m Would you be able to take a look? Thanks
