### ISSUE TITLE
`Primer::Beta::Link` is missing support for trainling and leading visuals

### ISSUE THREAD

**Issue by HDinger** [primer/view_components#2981]
# Steps to reproduce

* Go to the specification of the Link component and look at the anatomy: https://primer.style/components/link#anatomy 
* There is a support for trailing and leading visuals defined

<img width="400" alt="Bildschirmfoto 2024-07-30 um 07 48 27" src="https://github.com/user-attachments/assets/b94d0543-da2a-422d-b706-c064686280ce">

# Current behavior

* The Link component supports neither a trailing nor a leading visual

# Expected behavior

* There are slots for one leading and one trailing visual defined in the `Primer::Beta::Link` component

**Comment by lesliecdubs** [comment]
Thanks so much for contributing the PR! Primer engineers have been tagged for review so we'll try to take a look soon.
