### ISSUE TITLE
Align-end Action menu with long item label or description is misaligned

### ISSUE THREAD

**Issue by bsatarnejad** [primer/view_components#3000]
### Steps to reproduce

1. Go to the specification of the Action menu component and select Align end: https://primer-lookbook.github.com/view-components/lookbook/inspect/primer/alpha/action_menu/align_end
2. Add a **long** label or description for an item

### Current Behavior
As you see below, the action list is misaligned with button
![Screenshot of an align-end primer action menu with long description, which is misaligned with button](https://github.com/user-attachments/assets/60f2b97e-5587-43ad-b307-30690de134dd)

### Expected Behavior
The long text can be wrapped or truncated, and the action list should be aligned to the button. For example:
![Screenshot of an example for align-end primer action menu with long description, which is aligned with button](https://github.com/user-attachments/assets/edb5c806-bb2a-497d-bf7b-d66adccdb383)

**Comment by lesliecdubs** [comment]
Hi @bsatarnejad! Have you tried adding a `size` onto the `ActionMenu` to help control for this? We think "small" might help with this case. Let us know if that doesn't work.

**Comment by bsatarnejad** [comment]
Hi @lesliecdubs 
thanks a lot for your quick response.

I tested your solution, and it works. 👍
