### ISSUE TITLE
SegementedControl has the wrong color 

### ISSUE THREAD

**Issue by HDinger** [primer/view_components#3075]
### Steps to reproduce

* Create a segmented control with icons and text:

```
render(Primer::Alpha::SegmentedControl.new("aria-label": "File view", size: :medium)) do |component|
  component.with_item(label: "Preview", icon: :eye, selected: true)
  component.with_item(label: "Raw", icon: :"file-code")
  component.with_item(label: "Blame", icon: :people)
end
```

### Actual behavior

* The text is rendered in blue
* I assume that happend with the [update to primitives v9](https://github.com/primer/view_components/pull/3023) in the last version. Before it worked correctly

<img width="310" alt="Bildschirmfoto 2024-09-10 um 11 40 42" src="https://github.com/user-attachments/assets/a0e3a6cb-a484-491d-8181-67ba3d3c53bd">

### Expected

* The text should be black

<img width="301" alt="Bildschirmfoto 2024-09-10 um 11 41 37" src="https://github.com/user-attachments/assets/3fd2ac05-dec4-441b-a6bc-7c72f1d09d73">

### Environment

* OS: MacOs
* Browser: Chrome/Firefox
* Primer version: 0.33.0 ( was introduced just recently, in 0.31.0 it worked fine)

**Comment by jonrohan** [comment]
We're having trouble reproducing this, could you verify it's still broken and share a link if you have it?

**Comment by HDinger** [comment]
I can't reproduce this any more either. 🤷‍♂️ Thanks for having a look 🙇
