### ISSUE TITLE
Button that submits a value

### ISSUE THREAD

**Issue by dereke** [primer/view_components#3129]
I want to render a button that submits a form with a named value like this:

```html
<button type="submit" name="remove_thing" value="some-id">Remove thing</button>
```

I can't seem to get this to work as you can't seem to change a button component to submit:

```rb
form.button(
  type: :submit,
  name: "remove_thing",
  value: "some-id",
  label: "Remove thing"
)
```

I've also tried using a `form.submit()` but the label overrides the value.

Is there some other way of doing this?

**Comment by lesliecdubs** [comment]
Thanks for letting us know.

@camertron given your knowledge of our forms setup, could you take a look at this and weigh in?

**Comment by camertron** [comment]
Hey @dereke, thanks for bringing this up! Seems like an oversight 😄 This PR should fix it: https://github.com/primer/view_components/pull/3141

**Comment by dereke** [comment]
thanks so much for this!
