### ISSUE TITLE
Setting properties on a form control when using the form builder

### ISSUE THREAD

**Issue by dereke** [primer/view_components#3195]
I am trying to use the autocomplete component from within a form builder:

```ruby
class MyForm < ApplicationForm
  form do |form|
    form.auto_complete(
      name: :skills,
      label: "Skills",
      placeholder: "Search skills library",
      required: true,
      list_id: "skills_autocomplete",
      src: "/skills/autocomplete?select_fields=id,name,description&search_field=name",
    )
  end
end
```

This renders a `FormControl` with the autocomplete inside and that is all great. However I want to set the form control to be full width. There is a property for this available on the form control but that seems to be inaccessible from here.

Is there a way to modify the values passed to the form control so we can set properties on it?

Thanks for your help

**Comment by camertron** [comment]
Hey @dereke, thanks for bringing this to our attention 😄 It should be mitigated by https://github.com/primer/view_components/pull/3205 👍

**Comment by dereke** [comment]
Amazing - thanks so much! ❤️
