### ISSUE TITLE
Update any lingering non-functional color usage

### ISSUE THREAD

**Issue by srt32** [primer/view_components#324]
`Primer::Classify`

- [x] bg
- [x] color
- [x] border
- [x] box-shadow

We should remap the current uses to the correct functional classes like `bg: :green` to `color-bg-success-inverse`

https://primer-css-git-mkt-color-modes-docs-primer.vercel.app/css/support/v16-migration#text

**Comment by manuelpuyol** [comment]
Everything has been merged!
