### ISSUE TITLE
Button component applies button class

### ISSUE THREAD

**Issue by rmathew1992** [primer/view_components#405]
In our button component, we apply the button class. This means that if we wanted to style the button as a button link, the link styling gets overwritten. 

https://github.com/primer/view_components/blob/8b3821aef49386462b9d78f14eb27ebb206699e4/app/components/primer/button_component.rb#L62-L68

@joelhawksley and I ran into this when trying to update the summary of details component as a button link.

**Comment by joelhawksley** [comment]
Thanks for the report @rmathew1992! 

I think the resolution here is to add support for `btn-link`, not applying `btn` in that case.

**Comment by manuelpuyol** [comment]
This has been fixed in `v0.0.36`! https://github.com/primer/view_components/releases/tag/v0.0.36
