### ISSUE TITLE
Idea: don't set default tag for `Heading` component, restrict allowed tags, add more examples

### ISSUE THREAD

**Issue by khiga8** [primer/view_components#466]
Headings elements carry semantic meaning in conveying page hierarchy but it is often used mistakenly to convey stylistic meaning. Incorrect usage of headings can be confusing for screen reader users and detrimental to accessibility.

Proposed changes:
1.  Don't have any default tag and require the consumer to always pass it in.
- Currently the tag defaults to `:h1`. However, the heading level is largely dependent on the page/context it is to be used so it may not make sense to have a default. By not offering a fallback, we encourage the consumer to be intentional about heading levels.

2. Restrict the possible tags to `<h1>` ~ `<h6>` tags for this component
- Currently there are no restrictions. 

3. Add examples that dissociate heading levels from aesthetics.
- Often times, people using heading levels for stylistic purposes (e.g. they want a large text and so they use `<h1>`), but this should be discouraged. We should have examples in the documentation that disassociate heading levels from aesthetics (maybe examples using `font_size:`). We can also redirect the user to use the `Text` component with [relevant typography arguments](https://primer.style/view-components/system-arguments#typography) as an alternative.

**Comment by joelhawksley** [comment]
Fantastic! I am 👍🏻 to all of these suggestions. I think something like `HeadingComponent.new(tag: :h3, font_size: 1)` is the kind of example we need in the docs to emphasize this concern.
