### ISSUE TITLE
Idea: Add additional sections in docs around usage guidelines

### ISSUE THREAD

**Issue by khiga8** [primer/view_components#467]
Proposal: Modify `Rake` to allow additional docs sections aside from `Examples`, `Slots`. Update `templates/component.tt` with additional sections.

Potential sections: 
- Description of component and when to use. 
- Usage/Best practices (do this, don't do that, offer alternative components)
- Accessibility-related information to be aware of when using the component.

Reasons: 
1. Consumers of `primer/view_components` will likely rely heavily on the docs to make informed UI decisions. We should empower consumers to make informed decisions as easily as possible by surfacing relevant information through docs. Though we can have systemic code checks in place to prevent some bad decisions from being made, there are decisions that consumers may have to make for their specific context.
1. Having to document usage information also allows us to develop primer view components with relevant code checks in place. (e.g. putting in restrictions around allowed tags)

Side note:
I don't quite understand how yard works and if it's possible to add things like custom tags for new sections so got stuck in approaching this. If you are familiar, let's pair!

**Comment by joelhawksley** [comment]
@khiga8 after seeing the [USDS docs](https://designsystem.digital.gov/components/button-group/) during our pairing this morning, I think this is a great idea!

I _think_ we can achieve this with custom tags in YARD: https://rubydoc.info/gems/yard/file/docs/TagsArch.md#adding-custom-tags.

How about we start by adding an `accessibility` tag and see how that goes?

**Comment by koddsson** [comment]
The `:docs:build` task is getting big as well. Is it time for us to extract it into a gem to include back into the project?

**Comment by khiga8** [comment]
> The `:docs:build` task is getting big as well. Is it time for us to extract it into a gem to include back into the project?

@koddsson Maybe....? (cc: @joelhawksley @manuelpuyol )

I'm not sure what that looks like so happy to pair on it with you next week.

**Comment by joelhawksley** [comment]
I think that if nothing else, it should be written (and maybe tested) as a class. I don't think we'd want it in a separate repo if it's going to change a lot.

**Comment by manuelpuyol** [comment]
I agree that we need to extract it somehow. +1 on moving it to a class to be easier to update
