### ISSUE TITLE
Standardize what we call the component we are describing in documentation

### ISSUE THREAD

**Issue by khiga8** [primer/view_components#487]
In documentation, we are quite inconsistent in how we refer to the component we're describing. I am not sure if we've settled on one, but I think it'd be good to be on the same page about during code reviews.

AutoComplete
breadcrumbs
Primer::CounterComponent
`TimelineItem`

For consistency, let's pick one to go with moving forward! (I can update docs for existing ones as new ppl may reference existing practices).

Relates to #235 

cc: @manuelpuyol  @koddsson @joelhawksley

**Comment by joelhawksley** [comment]
@khiga8 you're right, this is pretty confusing!

My personal preference would be `TimelineItem`, especially once we remove `Component` from the names of all of the components. It makes it clear that we are referring to the Ruby object and not the name of a pattern or general concept, as some of our components have pretty generic names, such as button.

**Comment by khiga8** [comment]
@joelhawksley That makes sense to me! I'm onboard unless someone else has a strong case against it :-)
