### ISSUE TITLE
Remediate remaining CSS gaps

### ISSUE THREAD

**Issue by joelhawksley** [primer/view_components#557]
## Problem

In https://github.com/primer/view_components/pull/524, @jonrohan and I identified several cases where Primer ViewComponents outputs classnames that don't exist in Primer CSS.

## Solution

Remediate them so that this list is empty: https://github.com/primer/view_components/pull/524/files#diff-b99841b4c73b6bacd5aa5642b966afb8b73133b55ab8276a3c705b674ca68308R27

**Comment by jonrohan** [comment]
We're moving in this direction, but this Issue doesn't accurately describe the problem
