### ISSUE TITLE
JavaScript encapsulation

### ISSUE THREAD

**Issue by koddsson** [primer/view_components#561]
Behavioral ViewComponents ship with JavaScript. Since JavaScript can be global, we need some way of scoping the behavior we ship with Primer ViewComponents to be only applied to the ViewComponents that the library provides. By scoping the behaviors to just the Primer ViewComponents, we prevent accidentally interfacing with unrelated elements in the consuming app.

**Comment by koddsson** [comment]
@manuelpuyol This has already been fixed, right?

**Comment by manuelpuyol** [comment]
yeah I think it is safe to close this since we shipped https://github.com/primer/view_components/pull/574
