### ISSUE TITLE
Add ability to self-close BaseComponent tag

### ISSUE THREAD

**Issue by tobiasahlin** [primer/view_components#562]
### Problem

When using Primer::BaseComponent to build an `img`, it is not possible to have a self-closing `<img src...>` tag returned, nor a self-closing `source`.

### Proposed solution

Add an `self_close` option that uses `tag` instead of `content_tag`, or automatically detect HTML elements that are self-closing and exclude the trailing closing tag (e.g. `</img>`).

See: https://apidock.com/rails/ActionView/Helpers/TagHelper/content_tag, https://stackoverflow.com/questions/10388268/rails-helper-how-can-i-get-a-helper-to-give-me-a-br-or-other-markup/16473674

**Comment by manuelpuyol** [comment]
Closed by https://github.com/primer/view_components/pull/892

**Comment by manuelpuyol** [comment]
Closed by https://github.com/primer/view_components/pull/892
