### ISSUE TITLE
Add support for `width-full`

### ISSUE THREAD

**Issue by joelhawksley** [primer/view_components#638]
### Problem

System arguments do not support `width-full`.

### Proposed solution

Map `width: :full` to `width-full`.

**Comment by cheshire137** [comment]
I just ran into this not working in version 0.15.1 of the primer_view_components gem. Trying to make this view component have the `width-full` class:

```ruby
    Primer::BaseComponent.new(
      tag: :span,
      display: :flex,
      align_items: :center,
      justify_content: :space_between,
    )
```

If I pass `width: :full`, it adds a `width="full"` HTML attribute to the element, but if I pass classes: "width-full", it raises an exception:

> Use System Arguments (https://primer.style/view-components/system-arguments) instead of Primer CSS class name width-full. `width: "100%"` also results in a `width="100%"` HTML attribute on the element.

**Comment by cheshire137** [comment]
I opened https://github.com/primer/view_components/issues/2435 instead of reopening this old issue.
