### ISSUE TITLE
Add system arguments example for each component

### ISSUE THREAD

**Issue by joelhawksley** [primer/view_components#706]
In several recent cases, I've seen folks wrapping Primer ViewComponents in Primer CSS elements to achieve what they could with system arguments. For example:

```erb
<div class="mt-1">
  <%= render(Primer...) %>
</div>
```

When `mt-1` could have been passed to the Primer ViewComponent. In the interest of encouraging use of System Arguments, I think we should add an example for each component that shows how they might be used with the component.

**Comment by lesliecdubs** [comment]
Not stale. Also added this to our unprioritized backlog in case someone wants to pick it up.

**Comment by ollie-iterators** [comment]
It might be good if there was a list of components that need the system arguments examples, like for https://github.com/primer/view_components/issues/676 (The Issue about standardizing component names)
