### ISSUE TITLE
Fix Symbol /  String Discrepancy in Storybook Params 

### ISSUE THREAD

**Issue by natashaU** [primer/view_components#82]
@joelhawksley originally noticed this problem while updating the storybook for the flash and octicon component. 

While working on the following PR: https://github.com/primer/view_components/pull/79, I noticed I had the same issue.

Each time a selection is made to change the storybook from its default settings, the params render as a string rather than symbol ( Even though the keys in the hash are symbols), which prevents the user from making any sort of selection or change to the components in storybook. In order to work around this in a "hacky" way, we must add a `.to_sym` method to the variable that is being rendered in the component. 

It would probably be better if we could figure out a way to do this without adding `.to_sym` to every selection variable in all the view components???

cc/ @joelhawksley @aellispierce @jonspalmer

**Comment by jonspalmer** [comment]
Super excited that folks are using Storybook and ViewComponents in anger.

I'm trying to understand where we think the fix for this should be?

Is the issue with @storybook/server and the fact that control values are serialized over the wire as strings? (they kind of have to be given they're query params)  It's not obvious to me that we can solve this in a generic way in . I guess we could add to the `ViewComponent::Storybook` DSL to provide and flag that causes triggers conversion of strings to symbols. Feels a bit awkward but would work. Equally I could imagine `fetch_or_fallback` to be able to handle strings or types

**Comment by manuelpuyol** [comment]
Yeah, I've been haviong this problem creating stories too and it feels weird using `.to_sym` inside the component.

> Equally I could imagine fetch_or_fallback to be able to handle strings or types

I like this idea! we could treat `String` and `Symbol` as equals, wdyt @joelhawksley?

**Comment by joelhawksley** [comment]
@jonspalmer @manuelpuyol while I think we could solve in `fetch_or_fallback`, I'm hesitant to do so.

I don't think it's a good sign that we're considering making changes to our components to accommodate `view_component_storybook`. I'd much rather be able to be string in terms of which types our component accepts and have `view_component_storybook` provide the correct type.

@natashaU and I are going to do a spike to see how difficult this might be ❤️

**Comment by jonspalmer** [comment]
@joelhawksley You make a good point. I have an idea that its actually simple to support in `view_component_storybook` going to give it a shot.

**Comment by jonspalmer** [comment]
Just committed this which I think solves the problem here: https://github.com/jonspalmer/view_component_storybook/commit/5ee83a071a6f7cbdee6d8a55aaad6be5c65e6cc4

**Comment by joelhawksley** [comment]
@jonspalmer that looks good to me! I could see us running into similar issues with other types, but this is great for now 👍

**Comment by natashaU** [comment]
@jonspalmer this looks great and was very similar to what @joelhawksley and I were working on. Thank you!!
