### ISSUE TITLE
UnderlineNavComponent slots and responsive support

### ISSUE THREAD

**Issue by jonrohan** [primer/view_components#84]
We're wanting to package up the overflow functionality that the repository underline nav has and include it in the Primer view_component.

![image](https://user-images.githubusercontent.com/54012/93625328-9d701380-f996-11ea-9454-f2383694566a.png)

The current state of this code is that it uses `Primer::UnderlineNavComponent` but content areas to loop through a list of links once and re-loop through them again to render matching links in the main nav and dropdown nav. Ideally we should be able to provide `item` slots to the component and the responsive dropdown is generated automatically.

Here's what we'll need to do to get this support.

- [x] Convert `UnderlineNavComponent` to using the slots api
- [ ] By default render the overflow menu dropdown with the option to turn it off.
- [ ] Package up the js responsible for calculating when to overflow an item?

**Comment by danielnc** [comment]
@jonrohan was this solved? or how are you solving the problem? I am facing the exact same issue

**Comment by jonrohan** [comment]
I'm currently building an ActionBar component that will accomplish this, it's very experimental at the moment and will probably go through some breaking changes, but might be useful in figuring out how to do this. https://github.com/primer/view_components/pull/1339
