### ISSUE TITLE
Support negative margin utilities

### ISSUE THREAD

**Issue by jonrohan** [primer/view_components#96]
Primer css supports [Negative Margins](https://primer.style/css/utilities/margin#negative-margins) in the margin utilities. I've run into a situation a couple of times where I wanted to use a negative margin with a view component, but `ml: "n1"` doesn't work.

![image](https://user-images.githubusercontent.com/54012/94172606-8e320f80-fe47-11ea-9a23-6618445093a4.png)

**Comment by manuelpuyol** [comment]
hey @jonrohan could you try using `ml: -1`?

**Comment by jonrohan** [comment]
> hey @jonrohan could you try using `ml: -1`?

ah yeah, that works. Thanks!
