### ISSUE TITLE
JS Not working with new rails app 

### ISSUE THREAD

**Issue by muriloime** [primer/view_components#965]
Hi all, 

I followed the instructions as per https://primer.style/view-components/#installation in a new rails 7 app, but I get the following error

`The asset "primer.js" is not present in the asset pipeline.`

when adding javascript_include_tag. I guess for rails apps using sprockets it is needed to include in the documentation to add a primer line into manifest.js file too, however in this gem I only see exposed `primer_view_components.js`, not `primer.js`.

Many thanks

**Comment by camertron** [comment]
Hey @muriloime, thanks for bringing this up, and apologies for missing it! As you discovered, the fix is to use `<%= javascript_include_tag("primer_view_components") %>` instead. The docs should be fixed once [this PR](https://github.com/primer/view_components/pull/1191) lands.
