### ISSUE TITLE
Using border-dashed CSS class raises warning in development

### ISSUE THREAD

**Issue by laserlemon** [primer/view_components#992]
There appears to be no way to render a Primer view component with a dashed border. The [system arguments](https://primer.style/view-components/system-arguments) don't include any argument controlling the border style.

Primer CSS [supports dashed borders](https://primer.style/css/utilities/borders#border-style) but when I add the CSS class to my rendered Primer view component, an exception is raised in local development.

For example:

```erb
<%= render Primer::BoxComponent.new(border: true, classes: "border-dashed") do %>
  Hello, world!
<% end %>
```

The message of the exception is:

```
Use System Arguments (https://primer.style/view-components/system-arguments) instead of Primer CSS class name border-dashed. This warning will not be raised in production. Set PRIMER_WARNINGS_DISABLED=1 to disable this warning.
```

I'm unable to set `PRIMER_WARNINGS_DISABLED=1` as a long-term solution.

As always, thank you for your work on this amazing library of view components! 💛

**Comment by jonrohan** [comment]
👋🏻 Sorry for the late reply, I think you can use `border: :dashed` here to get the class you want. I'm going to investigate why it's not documented.
